### ISSUE TITLE
[MacOS] curses fails to render Unicode chars when LC_ALL="C"

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1000]
**Small description**

If the following is used: `export LC_ALL='C'` within a bash environment,  I get the following error when trying to load anything:

_curses.error: addwstr() returned ERR

No sheets are shown

**Expected result**
To be able to load the sheet :)

**Comment by saulpw** [comment]
Hi @geekscrapy, I could not reproduce this issue locally.  Can you include the version of VisiData, a sample file that does not load, and the backtrace of the error from `Ctrl+E`?

**Comment by geekscrapy** [comment]
This is running on macos 10.15.7 using the Terminal app running in bash (GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0) - default)

```# export LC_ALL='C'
# vd . --debug
```

I get the following error. I can't open the error sheet.

![image](https://user-images.githubusercontent.com/11225502/120612572-62e7d180-c466-11eb-97c7-16097554e9ec.png)

If I use the following though, it throws this exception: `vd . --debug`

```
Traceback (most recent call last):
  File "/Users/geekscrapy/py3.7/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/Users/geekscrapy/py3.7/lib/python3.7/site-packages/visidata/main.py", line 301, in vd_cli
    rc = main_vd()
  File "/Users/geekscrapy/py3.7/lib/python3.7/site-packages/visidata/main.py", line 266, in main_vd
    run(vd.sheets[0])
  File "/Users/geekscrapy/py3.7/lib/python3.7/site-packages/visidata/mainloop.py", line 290, in run
    ret = vd.mainloop(scr)
  File "/Users/geekscrapy/py3.7/lib/python3.7/site-packages/visidata/mainloop.py", line 144, in mainloop
    self.draw_all()
  File "/Users/geekscrapy/py3.7/lib/python3.7/site-packages/visidata/mainloop.py", line 90, in draw_all
    vd.draw_sheet(vd.win1, ss1[0])
  File "/Users/geekscrapy/py3.7/lib/python3.7/site-packages/visidata/mainloop.py", line 40, in draw_sheet
    self.exceptionCaught(e)
  File "/Users/geekscrapy/py3.7/lib/python3.7/site-packages/visidata/mainloop.py", line 38, in draw_sheet
    sheet.draw(scr)
  File "/Users/geekscrapy/py3.7/lib/python3.7/site-packages/visidata/sheets.py", line 721, in draw
    self.drawColHeader(scr, headerRow, numHeaderRows, vcolidx)
  File "/Users/geekscrapy/py3.7/lib/python3.7/site-packages/visidata/sheets.py", line 668, in drawColHeader
    scr.addstr(y+i, x+colwidth, C, sepcattr.attr)
_curses.error: addwstr() returned ERR
```

@ajkerrigan do you have a mac? Can you confirm this?

**Comment by ajkerrigan** [comment]
> @ajkerrigan do you have a mac? Can you confirm this?

I have a clunky mac in the cloud that I wake up just for cases like this! :grin: 

And yeah, I see the same thing. Usually when I see a weird locale-related issue though, the first step is to use a UTF one (in my case `en_US.UTF-8`). Is that feasible here or do you need that C locale for something else?

**Comment by geekscrapy** [comment]
It wasn't really an issue, tbh I can't remember now why I changed it (some script I used needed it) and I forgot about it being set.
So this issue is to capture the issue of it presented itself for someone else (as it's quite random and the error isn't that obvious), and if there is an easy fix, all the better!

**Comment by saulpw** [comment]
I'm guessing this is because `LC_ALL="C"` means "ASCII only", or "Unicode characters not allowed", and many of the default drawing characters are non-ASCII.  Seems like Linux curses hums along where MacOS curses refuses to draw them.  I'm undermotivated to fix this issue, especially we should all be using [UTF-8 everywhere](http://utf8everywhere.org/), but maybe it gets rolled up into another feature request eventually to get VisiData work on an old-school ASCII-only dumb terminal.
