### ISSUE TITLE
vds: cannot export sheets containing a date column

### ISSUE THREAD

**Issue by pacien** [saulpw/visidata#1008]
**Small description**

It's not possible to save a sheet to a .vds file if said sheet contains a date column.
This results in the error below.

**Expected result**

It should just work(tm).

**Actual result with screenshot**

```stacktrace
Traceback (most recent call last):
  File "/nix/store/srkr2wnwq95ylmgiadh28p3jiaadl5yw-visidata-2.4/lib/python3.8/site-packages/visidata/threads.py", line 215, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/nix/store/srkr2wnwq95ylmgiadh28p3jiaadl5yw-visidata-2.4/lib/python3.8/site-packages/visidata/loaders/vds.py", line 32, in save_vds
    fp.write(json.dumps(d)+NL)
  File "/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
```

**Steps to reproduce with sample data and a .vd**

❯ cat testsheet.vd
```log
sheet	col	row	longname	input	keystrokes	comment
visidata_menu			sheets-stack		S	open Sheets Stack: join or jump between the active sheets on the current stack
sheets		キsheets	add-row		a	append a blank row
sheets	name	キ	edit-cell	testsheet	e	edit contents of current cell
sheets		キtestsheet	open-row		^J	open sheet referenced in current row
testsheet	0		rename-col	testcol	^	edit name of current column
testsheet	testcol		type-date		@	set type of current column to date
testsheet			add-row		a	append a blank row
testsheet	testcol	0	edit-cell	2021-06-14	e	edit contents of current cell
testsheet			save-all	test.vds	g^S	save all sheets to given file or directory)
```

**Additional context**

Problem is present on v2.4 and on the develop branch (commit 3350d9fd8c9e64ebf409deae4b31085d12efeb7f)

**Comment by saulpw** [comment]
Thanks @pacien for both the bug report and the PR!
