### ISSUE TITLE
encoding: command line option not taken into account for piped data

### ISSUE THREAD

**Issue by pacien** [saulpw/visidata#1018]
**Small description**

The `--encoding` command line option does not seem to be taken into account when loading data from stdin.

**Expected result**

It should just work(tm).

**Actual result with screenshot**

❯ `cat file_containing_latin1_stuff.csv | vd --csv-delimiter ';' --encoding latin-1`

```
Traceback (most recent call last):
  File "/nix/store/mma80vygbn5vygw16nb1pkjz0nrrd6mq-visidata-2.4/bin/.vd-wrapped", line 7, in <module>
    visidata.main.vd_cli()
  File "/nix/store/mma80vygbn5vygw16nb1pkjz0nrrd6mq-visidata-2.4/lib/python3.8/site-packages/visidata/main.py", line 301, in vd_cli
    rc = main_vd()
  File "/nix/store/mma80vygbn5vygw16nb1pkjz0nrrd6mq-visidata-2.4/lib/python3.8/site-packages/visidata/main.py", line 215, in main_vd
    vs = vd.openSource(p, create=True, **opts) or vd.fail(f'could not open {p}')
  File "/nix/store/mma80vygbn5vygw16nb1pkjz0nrrd6mq-visidata-2.4/lib/python3.8/site-packages/visidata/_open.py", line 92, in openSource
    vs = vs or vd.openPath(p, filetype=filetype, create=create)
  File "/nix/store/mma80vygbn5vygw16nb1pkjz0nrrd6mq-visidata-2.4/lib/python3.8/site-packages/visidata/_open.py", line 73, in openPath
    return openfunc(p)
  File "/nix/store/mma80vygbn5vygw16nb1pkjz0nrrd6mq-visidata-2.4/lib/python3.8/site-packages/visidata/_open.py", line 104, in open_txt
    if options.delimiter in next(fp):    # peek at the first line
  File "/nix/store/mma80vygbn5vygw16nb1pkjz0nrrd6mq-visidata-2.4/lib/python3.8/site-packages/visidata/path.py", line 281, in __next__
    return next(self.iter)
  File "/nix/store/mma80vygbn5vygw16nb1pkjz0nrrd6mq-visidata-2.4/lib/python3.8/site-packages/visidata/path.py", line 300, in __next__
    r = next(self.rf.iter_lines)
  File "/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 176: invalid continuation byte
```

**Additional context**

Version: issue affects v2.4 and the tip of the develop branch (commit 3350d9fd8c9e64ebf409deae4b31085d12efeb7f)

**Comment by saulpw** [comment]
Thanks for the issue, @pacien!  This was an interesting issue, which I've solved partially with the linked commit, but ultimately uncovered a larger issue, which is that `vd.options.foo` uses the top sheet as the options context, instead of using 'no sheet'; this was a hack to accommodate the legacy `options.foo` usages which have been around since before there were sheet-specific options.  To fix another tricky issue with playback we had awhile ago, if the sheets stack is empty, we made the cmdlog be the top sheet (and thus the options context); and since the cmdlog encoding is now explicitly set to utf-8 (to fix #1016), that made it ignore the `--encoding` when opening a .txt file to check if it's actually a .tsv (which is where this is failing).

In any event, a better solution will eventually involve making sure that all `options.foo` are properly scoped with their proper options context, and then changing `vd.options.foo` to explicitly ignore the current sheet context for cases like this.  But for now this use case should Just Work™.  (Though note that the given command line will not; it also would need `-f csv`, which should have made this bug not happen in the first place).
