### ISSUE TITLE
curcol not available in addcol-sh

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1031]
**Small description**
`echo $curcol` results in the following error.

**Expected result**
A column with the same data as `curcol` as if you had used `=` and the expr "`curcol`".

**Error**
```
Traceback (most recent call last):
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/sheets.py", line 132, in __getitem__
    i = self._keys.index(colid)
ValueError: 'curcol' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/sheets.py", line 140, in __getitem__
    c = self._lcm[colid]
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/basesheet.py", line 32, in __getitem__
    return self.locals[k]
KeyError: 'curcol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/shell.py", line 65, in calcValue
    args.append(shlex.quote(str(context[arg[1:]])))
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/sheets.py", line 146, in __getitem__
    raise KeyError(colid)
KeyError: 'curcol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/threads.py", line 219, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/threads.py", line 28, in _func
    d[k] = func(*args, **kwargs)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/shell.py", line 73, in calcValue
    vd.exceptionCaught(e)
NameError: name 'vd' is not defined
```

**Additional context**
vd commit: 911f15e52560bab8e751ade98050bbf98b0424e9

**Comment by saulpw** [comment]
I believe this is a dup of #989.  Please let me know if you meant something else.
