### ISSUE TITLE
[v2.6dev] Provide friendly error for empty files

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1047]
**Small description**
I attempted to open a few files with `vd *.log`. This resulted in the following error:
```
Traceback (most recent call last):
  File "/Users/geekscrapy/py3.7/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/Users/geekscrapy/py3.7/lib/python3.7/site-packages/visidata/main.py", line 320, in vd_cli
    rc = main_vd()
  File "/Users/geekscrapy/py3.7/lib/python3.7/site-packages/visidata/main.py", line 223, in main_vd
    vs = vd.openSource(p, create=True, **opts) or vd.fail(f'could not open {p}')
  File "/Users/geekscrapy/py3.7/lib/python3.7/site-packages/visidata/_open.py", line 99, in openSource
    vs = vd.openPath(Path(p), filetype=filetype, create=create)  # convert to Path and recurse
  File "/Users/geekscrapy/py3.7/lib/python3.7/site-packages/visidata/_open.py", line 82, in openPath
    return openfunc(p)
  File "/Users/geekscrapy/py3.7/lib/python3.7/site-packages/visidata/_open.py", line 113, in open_txt
    if options.delimiter in next(fp):    # peek at the first line
  File "/Users/geekscrapy/py3.7/lib/python3.7/site-packages/visidata/path.py", line 59, in __next__
    r = next(self.fp)
StopIteration
```
After a bit of troubleshooting I figured out that it was due to a file with empty contents (like that created with `touch test`, md5 hash `d41d8cd98f00b204e9800998ecf8427e`) that was causing the issue.

**Expected result**
To open all the files, not hard crash and probably provide some user feedback. Those files which are empty, add a dummy sheet (so you can track those that don't open). Maybe the dummy sheet doesn't open, or has no rows - so it is still joinable?

**Steps to reproduce with sample data and a .vd**
1. `touch test`
2. `vd test`

**Comment by anjakefala** [comment]
Thanks for making an issue @geekscrapy! This is legit.

**Comment by anjakefala** [comment]
Thanks for bringing this to our attention @geekscrapy! On default, it will open a blank sheet with that filetype name. 

This was handled for the case when `open_txt` is called.
