### ISSUE TITLE
[syscopy-selected] yanking as type "fixed" produces error

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1060]
**Small description**
I attempt to yank as "fixed" (rather than tsv/csv etc.) and I get the following error

**Expected result**
To copy rows as the format "fixed" to the system clipboard without error

**Actual result with screenshot**

```python
Traceback (most recent call last):
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/threads.py", line 219, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/loaders/fixed_width.py", line 77, in save_fixed
    with p.open_text(mode='w', encoding=vsheets.options.encoding) as fp:
AttributeError: 'tuple' object has no attribute 'options'
```

**Steps to reproduce with sample data and a .vd**
Open any sheet, `syscopy-selected`, change the format to "fixed"

**Comment by anjakefala** [comment]
Thanks for the bug report @geekscrapy! Apparently, the fixed saver needed some fixing. This should work now on the `develop` branch. =)
