### ISSUE TITLE
[join-sheets] friendly message when one of the joining sheets is missing the keycol

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1061]
I tried to join two sheets, one of which I had forgotten to select the keycolumn on. This provided the following error which isn't overly friendly to new users.

```python
Traceback (most recent call last):
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/threads.py", line 219, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/join.py", line 128, in reload
    self.addColumn(JoinKeyColumn(cols[0].name, keycols=cols)) # ColumnItem(c.name, i, sheet=sheets[0], type=c.type, width=c.width)))
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by anjakefala** [comment]
Agreed! That is not a friendly message. Good suggestion.
