### ISSUE TITLE
[2.7dev] [undo] KeyError on DirSheet when using undo

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1133]
**Small description**
The undo functionality seems to work, but results in an error on a DirSheet. I tried `delete-cell` command. 

**Expected result**
No error

**Actual result with screenshot**
```
Traceback (most recent call last):
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/basesheet.py", line 161, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/basesheet.py", line 66, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "undo-last", line 1, in <module>
    # import plugins.sparkline
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/undo.py", line 41, in undo
    undofunc(*args, **kwargs)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/modify.py", line 66, in _undoCellChanged
    _, rowmods = col.sheet._deferredMods[col.sheet.rowid(row)]
KeyError: 4594777104
```

**Steps to reproduce with sample data and a .vd**
vd . --config=/dev/null
Delete a cell on this sheet with 'delete-cell'

**Comment by anjakefala** [comment]
>  The undo functionality seems to work, but results in an error on a DirSheet. I tried delete-cell command.

This is a current limitation with undo, and sheets that have track changes! Things will all work, but this error will display, and has been hard for me to completely untangle. 

 I will give it another shot.

Thanks for reporting!

**Comment by saulpw** [comment]
Fixed, will be in next release.
