### ISSUE TITLE
Ctrl-q exits with ModuleNotFoundError

### ISSUE THREAD

**Issue by eigenfoo** [saulpw/visidata#1155]
**Small description**

Exiting Visidata with Ctrl-q ([as documented here](https://www.visidata.org/docs/pipes/)) fails with a `ModuleNotFoundError` for `plugins`

**Expected result**

Exit successfully with the current sheet in stdout.

**Actual result with screenshot**

```bash
(base) george@eigenfoo.local:~
$ vd  # Ctrl-q to exit
Traceback (most recent call last):
  File "/usr/local/Cellar/visidata/2.6.1/libexec/lib/python3.9/site-packages/visidata/settings.py", line 364, in loadConfigAndPlugins
    vd.addGlobals(importlib.import_module(modname).__dict__)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugins'
```

**Steps to reproduce with sample data and a .vd**

N/A

**Additional context**

I think the issue comes in the following lines, as `ModuleNotFoundError` is not a subclass of `Exception`... but I'm not even sure what `plugins` module I'm even supposed to have? 

https://github.com/saulpw/visidata/blob/666e30329878b74678d24c300e1c50ceb7aa0666/visidata/settings.py#L363-L367

```bash
>>> isinstance(ModuleNotFoundError, Exception)
False
```

```bash
(base) george@eigenfoo.local:~
$ vd --version  # Installed via brew
saul.pw/VisiData v2.6.1
```

**Comment by anjakefala** [comment]
Thanks so much @eigenfoo! We have a fix on `develop` noted here: https://github.com/saulpw/visidata/issues/1145

I should probably escalate this fix for a potential patch (2.6.2), because I think this is one of the few bugs where multiple people independently came forward about it!
