### ISSUE TITLE
[develop] Updating *.gz files corrupts archives

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#1159]
**Small description**
When saving a `.json.gz`, the next time the archive is opened, we get this stacktrace:

```
Traceback (most recent call last):
  File "/home/kefala/git/visidata/visidata/loaders/json.py", line 38, in iterload
    ret = json.loads(L, object_hook=AttrDict)
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kefala/git/visidata/visidata/threads.py", line 206, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/home/kefala/git/visidata/visidata/sheets.py", line 289, in reload
    for r in self.iterload():
  File "/home/kefala/git/visidata/visidata/loaders/json.py", line 50, in iterload
    ret = json.load(fp)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.8/gzip.py", line 498, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Expected result**
Saved archives can be opened as before.

**Steps to reproduce with sample data and a .vd**

```
vd sample_data/y77-th95.json.gz
Ctrl+S
vd sample_data/y77-th95.json.gz
```

**Additional context**
First commit: d40361aa2d1649e49f0cfd623687114e4a231ec6

**Comment by anjakefala** [comment]
A minimum diff to revert the issue:

```
Binary files a/sample_data/y77d-th95.json.gz and b/sample_data/y77d-th95.json.gz differ
diff --git a/visidata/path.py b/visidata/path.py
index 0b0c3ade..481a1fb6 100644
--- a/visidata/path.py
+++ b/visidata/path.py
@@ -46,11 +46,6 @@ class FileProgress:
             gerund = 'nothing'
 
         # track Progress on original fp
         self.fp_orig_read = self.fp.read
         self.fp_orig_close = self.fp.close
-        self.fp.read = self.read
-        self.fp.close = self.close
-
         if self.prog:
             self.prog.__enter__()
 
@@ -61,7 +56,7 @@ class FileProgress:
         return self.fp_orig_close(*args, **kwargs)
 
```

Both `fp_orig_read` and `fp_orig_close` needed to be reverted.

**Comment by anjakefala** [comment]
Reverted here: https://github.com/saulpw/visidata/commit/779a22418c6fc86351dbd3b46badd1b6fdbc711e

#1175 was opened to investigate a better solution.
