### ISSUE TITLE
[splitwin-input] crashes when >96 is used

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1166]
**Small description**
I was just trying out split win and came across this issue. I appreciate that a window of less than a row height is not super useful, but it is a halting bug.

**Expected result**
To be told that the value is not valid, and not crash

**Actual result**

```
Traceback (most recent call last):
  File "/Users/geekscrapy/Documents/pyv/py3.7/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/main.py", line 327, in vd_cli
    rc = main_vd()
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/main.py", line 292, in main_vd
    run(vd.sheets[0])
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/vdobj.py", line 34, in _vdfunc
    return func(visidata.vd, *args, **kwargs)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/mainloop.py", line 329, in run
    ret = vd.mainloop(scr)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/mainloop.py", line 195, in mainloop
    vd.setWindows(vd.scrFull)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/mainloop.py", line 70, in setWindows
    vd.winBottom = scr.derwin(h-n-topmenulines, w, n+topmenulines, 0)
_curses.error: curses function returned NULL
```

**Steps to reproduce with sample data and a .vd**
`vd .`

```
sheet	col	row	longname	input	keystrokes	comment
			open-file	.	o	
			splitwin-input	99	zShift+Z	set split pane to specific size
```
vd crashes

**Additional context**
Commit: 29d9ea3ba1d0f250650593977fb11ad29886311f

**Comment by saulpw** [comment]
Thanks for the bug, @geekscrapy, it's fixed now.
