### ISSUE TITLE
[develop] Trouble running VisiData with `TERM` set to 'xterm'

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#1232]
(This might be a completely separate error from @ajkerrigan, neverless I can't run visidata without exporting the TERM variable.)

I ran into a similar issue today. I can reproduce/fix my particular error on Docker.

You might want to try running `TERM=xterm-256color visidata` on your system.

## to reproduce
```
$ docker run -it --rm --entrypoint /bin/bash python:3
$ pip install visidata
$ vd
Traceback (most recent call last):
  File "/usr/local/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/usr/local/lib/python3.10/site-packages/visidata/main.py", line 327, in vd_cli
    rc = main_vd()
  File "/usr/local/lib/python3.10/site-packages/visidata/main.py", line 292, in main_vd
    run(vd.sheets[0])
  File "/usr/local/lib/python3.10/site-packages/visidata/vdobj.py", line 34, in _vdfunc
    return func(visidata.vd, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/visidata/mainloop.py", line 333, in run
    ret = vd.mainloop(scr)
  File "/usr/local/lib/python3.10/site-packages/visidata/mainloop.py", line 201, in mainloop
    self.draw_all()
  File "/usr/local/lib/python3.10/site-packages/visidata/mainloop.py", line 105, in draw_all
    vd.draw_sheet(vd.win1, ss1[0])
  File "/usr/local/lib/python3.10/site-packages/visidata/mainloop.py", line 30, in draw_sheet
    scr.bkgd(' ', colors.color_default)
  File "/usr/local/lib/python3.10/site-packages/visidata/color.py", line 62, in __getattr__
    return self.get_color(optname).attr
  File "/usr/local/lib/python3.10/site-packages/visidata/color.py", line 153, in get_color
    r = self.colorcache[optname] = self._colornames_to_cattr(colornamestr, precedence)
  File "/usr/local/lib/python3.10/site-packages/visidata/color.py", line 121, in _colornames_to_cattr
    fg, bg, attrlist = self.split_colorstr(colornamestr)
  File "/usr/local/lib/python3.10/site-packages/visidata/color.py", line 93, in split_colorstr
    if self._get_colornum(x) is not None:   # only set known colors
  File "/usr/local/lib/python3.10/site-packages/visidata/color.py", line 114, in _get_colornum
    curses.init_pair(255, r, 0)
ValueError: Color pair is greater than COLOR_PAIRS-1 (63).
```

## solution
```
$ export TERM=xterm-256color
$ vd
# works as expceted
```

_Originally posted by @ryanmjacobs in https://github.com/saulpw/visidata/issues/1227#issuecomment-986263796_

**Comment by anjakefala** [comment]
`TERM` in this docker container is set to `xterm`.

**Comment by anjakefala** [comment]
This fix https://github.com/saulpw/visidata/pull/1231, will also fix this issue. VisiData will work with a terminal with only 16-colours (there are not 16-based colours for every colour option, but it is use-able, and pare-able).
