### ISSUE TITLE
`AttributeError` executing `vd.addUndo` during `unset`

### ISSUE THREAD

**Issue by ajkerrigan** [saulpw/visidata#1267]
**Small description**

If I unset an option, I see an `AttributeError` trying to append to a non-existent `undofuncs` object.

**Expected result**

The option is unset, with no error raised.

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

```
Traceback (most recent call last):
  File "/home/aj/code/visidata/visidata/basesheet.py", line 165, in execCommand
    hookfunc(self, cmd, '', keystrokes)
  File "/home/aj/code/visidata/visidata/cmdlog.py", line 178, in beforeExecHook
    self.afterExecSheet(sheet, False, '')
  File "/home/aj/code/visidata/visidata/macros.py", line 54, in afterExecSheet
    cmdlog.afterExecSheet.__wrapped__(cmdlog, sheet, escaped, err)
  File "/home/aj/code/visidata/visidata/cmdlog.py", line 214, in afterExecSheet
    if not sheet.cmdlog.rows or vd.isLoggableCommand(vd.activeCommand.longname):
  File "/home/aj/code/visidata/visidata/extensible.py", line 48, in dofunc
    return func(self)
  File "/home/aj/code/visidata/visidata/cmdlog.py", line 422, in cmdlog
    return CommandLog(sheet.name+'_cmdlog', source=sheet, rows=rows)
  File "/home/aj/code/visidata/visidata/extensible.py", line 14, in newinit
    oldinit(self, *args, **kwargs)
  File "/home/aj/code/visidata/visidata/extensible.py", line 14, in newinit
    oldinit(self, *args, **kwargs)
  File "/home/aj/code/visidata/visidata/sheets.py", line 184, in __init__
    super().__init__(*names, **kwargs)
  File "/home/aj/code/visidata/visidata/extensible.py", line 14, in newinit
    oldinit(self, *args, **kwargs)
  File "/home/aj/code/visidata/visidata/extensible.py", line 14, in newinit
    oldinit(self, *args, **kwargs)
  File "/home/aj/code/visidata/visidata/extensible.py", line 14, in newinit
    oldinit(self, *args, **kwargs)
  [Previous line repeated 4 more times]
  File "/home/aj/code/visidata/visidata/basesheet.py", line 94, in __init__
    self.names = names
  File "/home/aj/code/visidata/visidata/basesheet.py", line 192, in names
    self.name = self.options.name_joiner.join(self.maybeClean(str(x)) for x in self._names)
  File "/home/aj/code/visidata/visidata/basesheet.py", line 203, in name
    vd.addUndo(setattr, self, '_names', self._names)
  File "/home/aj/code/visidata/visidata/undo.py", line 29, in addUndo
    r.undofuncs.append((undofunc, args, kwargs))
AttributeError: 'NoneType' object has no attribute 'append'
```

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

- From inside a fresh VisiData session, go to the Options sheet
- Unset any option

Or, save this command log to `unset-undo-error.vdj`:

```
#!vd -p
{"longname": "open-file", "input": ".", "keystrokes": "o"}
{"sheet": "global", "row": "save_filetype", "longname": "unset-option", "input": "vdj", "keystrokes": ""}
```

And run `vd -p unset-undo-error.vdj`. 

**Additional context**
Please include the version of VisiData.

v2.9dev ( ff81d47 )

Note: After I hit this error, my subsequent commands took a couple tries before they went through. I also needed a successful command before Ctrl+E showed the error.

**Comment by saulpw** [comment]
Weird, I can't reproduce this issue, @ajkerrigan.  Does anyone else see this?

**Comment by anjakefala** [comment]
I do! After running @ajkerrigan's replay, you need to execute a command, any command.

**Comment by saulpw** [comment]
ohh, I see.  Got it.
