### ISSUE TITLE
[v2.9dev] [toggle-profile] name 'threading' is not defined

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1274]
**Small description**
Logging this quickly so I don't forget. Should be enough to replicate though.

**Expected result**
To start profiling

**Actual result with screenshot**
`vd . --config=/dev/null` > `toggle-profile`

```
Traceback (most recent call last):
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/basesheet.py", line 167, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/basesheet.py", line 69, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "toggle-profile", line 1, in <module>
    'VisiData: a curses interface for exploring and arranging tabular data'
NameError: name 'threading' is not defined
```

**Comment by saulpw** [comment]
Thanks @geekscrapy!  Fixed in fdbd820cd2d16854dc017b393049ee4fa1e3be7b.
