### ISSUE TITLE
Confusing error message when trying to open a .feather file at the command line without pyarrow

### ISSUE THREAD

**Issue by theosanderson** [saulpw/visidata#1278]
**Small description**
If you try to directly open a .feather file with `visidata my_file.feather`, but you don't have the `pyarrow` library installed, the (expected) error message instructing you to install pyarrow is obfuscated by a further error message relating to `curses`. If you open visidata and then open the file, behaviour is normal.

(Low priority issue)

**Expected result**
```$ visidata /Users/sandert/taxonium/backend/database/database.feather
You must install pyarrow to import feather files
```

**Actual result**
```$ visidata /Users/sandert/taxonium/backend/database/database.feather
Traceback (most recent call last):
  File "/Users/sandert/miniconda3/envs/armadillin/lib/python3.9/site-packages/visidata/mainloop.py", line 326, in run
    vd.push(vs)
  File "/Users/sandert/miniconda3/envs/armadillin/lib/python3.9/site-packages/visidata/sheets.py", line 1056, in push
    vs.ensureLoaded()
  File "/Users/sandert/miniconda3/envs/armadillin/lib/python3.9/site-packages/visidata/basesheet.py", line 213, in ensureLoaded
    return self.reload()   # likely launches new thread
  File "/Users/sandert/miniconda3/envs/armadillin/lib/python3.9/site-packages/visidata/loaders/_pandas.py", line 124, in reload
    df = readfunc(str(self.source), **options.getall('pandas_'+filetype+'_'))
  File "/Users/sandert/miniconda3/envs/armadillin/lib/python3.9/site-packages/pandas/io/feather_format.py", line 123, in read_feather
    import_optional_dependency("pyarrow")
  File "/Users/sandert/miniconda3/envs/armadillin/lib/python3.9/site-packages/pandas/compat/_optional.py", line 118, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'pyarrow'.  Use pip or conda to install pyarrow.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sandert/miniconda3/envs/armadillin/bin/visidata", line 8, in <module>
    sys.exit(vd_cli())
  File "/Users/sandert/miniconda3/envs/armadillin/lib/python3.9/site-packages/visidata/main.py", line 324, in vd_cli
    rc = main_vd()
  File "/Users/sandert/miniconda3/envs/armadillin/lib/python3.9/site-packages/visidata/main.py", line 289, in main_vd
    run(vd.sheets[0])
  File "/Users/sandert/miniconda3/envs/armadillin/lib/python3.9/site-packages/visidata/vdobj.py", line 31, in _vdfunc
    return func(visidata.vd, *args, **kwargs)
  File "/Users/sandert/miniconda3/envs/armadillin/lib/python3.9/site-packages/visidata/mainloop.py", line 331, in run
    curses.endwin()
_curses.error: must call initscr() first
```

**Additional context**
v2.6

**Comment by anjakefala** [comment]
> _curses.error: must call initscr() first

Thank you for the bug report! =) I agree: I pushed a fix for this in [v2.8](https://github.com/saulpw/visidata/blob/stable/CHANGELOG.md#bugfixes).

**Comment by theosanderson** [comment]
Sorry not to have checked!

**Comment by anjakefala** [comment]
@theosanderson It is completely okay! This was such a minor cosmetic fix, that I thought no one but me would notice, and I feel heartwarmed that someone explicitly asked for it.
