### ISSUE TITLE
rec.py addColumn bug

### ISSUE THREAD

**Issue by pyglot** [saulpw/visidata#1414]
**Short description**
When loading a .rec file vd fails with no data loaded. Adding `--batch --debug` provides a trace.

```sh
opening test.rec as rec
This message was left intentionally blank.
Traceback (most recent call last):
  File "/home/user/repos/visidata/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/home/user/.local/lib/python3.9/site-packages/visidata-2.9.dev0-py3.9.egg/visidata/main.py", line 339, in vd_cli
  File "/home/user/.local/lib/python3.9/site-packages/visidata-2.9.dev0-py3.9.egg/visidata/main.py", line 264, in main_vd
  File "/home/user/.local/lib/python3.9/site-packages/visidata-2.9.dev0-py3.9.egg/visidata/sheets.py", line 1061, in push
  File "/home/user/.local/lib/python3.9/site-packages/visidata-2.9.dev0-py3.9.egg/visidata/basesheet.py", line 225, in ensureLoaded
  File "/home/user/.local/lib/python3.9/site-packages/visidata-2.9.dev0-py3.9.egg/visidata/vdobj.py", line 23, in _execAsync
  File "/home/user/.local/lib/python3.9/site-packages/visidata-2.9.dev0-py3.9.egg/visidata/main.py", line 219, in <lambda>
  File "/home/user/.local/lib/python3.9/site-packages/visidata-2.9.dev0-py3.9.egg/visidata/sheets.py", line 290, in reload
  File "/home/user/.local/lib/python3.9/site-packages/visidata-2.9.dev0-py3.9.egg/visidata/loaders/rec.py", line 107, in iterload
  File "/home/user/.local/lib/python3.9/site-packages/visidata-2.9.dev0-py3.9.egg/visidata/loaders/rec.py", line 37, in addColumn
TypeError: 'ItemColumn' object is not iterable
```

**Possible fix**
In the following lines 
https://github.com/saulpw/visidata/blob/5c29abe99df22365adb13ab211c3aba84bdad7ad/visidata/loaders/rec.py#L34-L38

Changing `cols` to `*cols` appears to fix the bug. 

```python3
class RecSheet(TableSheet): 
     def addColumn(self, *cols, index=None): 
         super().addColumn(*cols, index=index) 
         self.colnames.update({col.name: col for col in cols}) 
         return cols[0] 
```

**test.rec**

The .rec file that was tested

```
%rec: test

Register: chip_id
Field:
Reg_width: 32
Address: 0x00
Bits:
Reset:
Description: Chip and version ID register

Register:
Field: product_id
Reg_width:
Address:
Bits: 16
Reset: 0x5201
Description: Product ID
+ 0x5201

```

**Comment by saulpw** [comment]
Thanks for doing all the legwork on this, @pyglot!  I've committed the fix now, but in the future, you can just submit a PR with the fix.  It would have gotten merged faster and you would have gotten commit credit.  Either way this is fixed now.

**Comment by pyglot** [comment]
Thanks! The reason I didn't file a PR is I would have to learn the flow and I didn't have time. Maybe next time :)
