### ISSUE TITLE
 [unzip-http] Stack traces with extracting files & panda loading

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1430]
Related to: https://github.com/saulpw/visidata/discussions/1413

**Small description**
Found a couple stack traces with a unzip-http

**Expected result**

- File(s) are extracted and saved locally
- dta file is loaded.

**Actual result with screenshot**
https://asciinema.org/a/MHBJevdgyKtv112xYqDvPJE6G

**Steps to reproduce with sample data and a .vd**

```
vd https://www.cgdev.org/technology-diffusion-paper-final-datasets
```

Try any of the extract commands, such as `x`:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/threads.py", line 206, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/loaders/archive.py", line 58, in extract
    self.zfp.extractall(members=[r.filename], path=path)
AttributeError: 'list' object has no attribute 'filename'
```

Load one of the dta files (It possible this is specific to my environment):

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 169, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 69, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "open-row", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 1061, in push
    vs.ensureLoaded()
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 227, in ensureLoaded
    return self.reload()   # likely launches new thread
  File "/usr/lib/python3.9/site-packages/visidata/loaders/_pandas.py", line 124, in reload
    df = readfunc(str(self.source), **options.getall('pandas_'+filetype+'_'))
  File "/usr/lib/python3.9/site-packages/pandas/io/stata.py", line 2004, in read_stata
    reader = StataReader(
  File "/usr/lib/python3.9/site-packages/pandas/io/stata.py", line 1151, in __init__
    with get_handle(
  File "/usr/lib/python3.9/site-packages/pandas/io/common.py", line 798, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'CHATTING_SPLICED.dta'
```

**Additional context**
Please include the version of VisiData. Latest version of develop.

**Comment by saulpw** [comment]
I believe this is fixed now.  Thanks for drawing attention to it!

**Comment by frosencrantz** [comment]
This works great now.  No issues. Thanks Saul and Anja!
