### ISSUE TITLE
[unzip-http] FreqTableSheet open-row created sheet doesn't load links

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1458]
**Small description**
FreqTableSheet open-row created sheet doesn't load links

**Expected result**
Links would be loaded.

**Actual result with screenshot**
https://asciinema.org/a/DyJoj2OPxS57yHaKlxeyvWgO7

```
Traceback (most recent call last):
  File "/home/felix/git/visidata/env/lib/python3.9/site-packages/visidata/basesheet.py", line 169, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/home/felix/git/visidata/env/lib/python3.9/site-packages/visidata/basesheet.py", line 69, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "open-row", line 1, in <module>
  File "/home/felix/git/visidata/env/lib/python3.9/site-packages/visidata/loaders/archive.py", line 49, in openRow
    fp = self.openZipFile(self.zfp, fi)
  File "/home/felix/git/visidata/env/lib/python3.9/site-packages/visidata/loaders/archive.py", line 64, in zfp
    return zipfile.ZipFile(str(self.source), 'r')
  File "/usr/lib/python3.9/zipfile.py", line 1239, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'technology-diffusion-paper-final-datasets'
```

**Steps to reproduce with sample data and a .vd**

Note this is an issue with 'Enter'/`open-row`.  It looks like links on a sheet created by 'gEnter'/`dive-row` works.
```
vd https://www.cgdev.org/technology-diffusion-paper-final-datasets
```
Hit 'F' to get to the FreqTableSheet.  Hit Enter to open-row, now you are on a new ZipSheet.  Hit Enter, get the stack trace for FileNotFoundError.  The data doesn't load properly.

  
**Additional context**
Please include the version of VisiData. Latest version of develop. 

Not sure if this is already a known error.  The GitHub actions are only running test_commands, which is failing on `addcol-sh`.  The Cmdlog tests are not being run.

**Comment by saulpw** [comment]
Thanks, @frosencrantz!  This is very helpful.  Should be fixed now.
