### ISSUE TITLE
[zip] ValueError: Attempt to use ZIP archive that was already closed

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1492]
**Small description**
When opening an inner file from within a zip, I get the attached error.

**Expected result**
To be able to open an embedded file like previous

**Actual result with screenshot**

```python
Traceback (most recent call last):
  File "/Users/geekscrapy/envs3/envs/py37/lib/python3.7/site-packages/visidata/basesheet.py", line 169, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/Users/geekscrapy/envs3/envs/py37/lib/python3.7/site-packages/visidata/basesheet.py", line 69, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "open-row", line 1, in <module>
    import plugins.agg_counter
  File "/Users/geekscrapy/envs3/envs/py37/lib/python3.7/site-packages/visidata/loaders/archive.py", line 49, in openRow
    fp = self.openZipFile(self.zfp, fi)
  File "/Users/geekscrapy/envs3/envs/py37/lib/python3.7/site-packages/visidata/loaders/archive.py", line 40, in openZipFile
    return fp.open(*args, **kwargs)
  File "/Users/geekscrapy/envs3/envs/py37/lib/python3.7/zipfile.py", line 1491, in open
    "Attempt to use ZIP archive that was already closed")
ValueError: Attempt to use ZIP archive that was already closed

```

**Steps to reproduce with sample data and a .vd**
1. Open a .zip file
2. Attempt to open an inner file with ENTER

**Additional context**
saul.pw/VisiData v2.10dev

**Comment by saulpw** [comment]
Thanks, @geekscrapy !  Should be fixed now.

**Comment by geekscrapy** [comment]
Great! I was actually hesitant to report this as it seemed so big and it worked for such a long time that I thought it was my environment and I presumed there was a test for it

**Comment by saulpw** [comment]
Good call, we probably should add tests for basic .zip file opening.
