### ISSUE TITLE
[input paste] Stack trace pasting via Ctrl+Y a Path into input

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1546]
**Small description**
Stack trace pasting via Ctrl+Y a Path into input

**Expected result**
Path is inserted into the input

**Actual result with screenshot**
https://asciinema.org/a/BgHT9ekrhojlwRuRhCV1qQLK7

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 182, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 69, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "open-file", line 1, in <module>
    'VisiData: a curses interface for exploring and arranging tabular data'
  File "/usr/lib/python3.9/site-packages/visidata/_open.py", line 9, in inputFilename
    return vd.input(prompt, type="filename", *args, completer=_completeFilename, **kwargs).strip()
  File "/usr/lib/python3.9/site-packages/visidata/_input.py", line 332, in input
    ret = self.editText(sheet.windowHeight-1, promptlen, sheet.windowWidth-promptlen-rstatuslen-2,
  File "/usr/lib/python3.9/site-packages/visidata/_input.py", line 270, in editText
    v = vd.editline(vd.activeSheet._scr, y, x, w, display=display, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/_input.py", line 230, in editline
    elif ch == '^Y':                           v = splice(v, i, vd.memory.clipval)
  File "/usr/lib/python3.9/site-packages/visidata/_input.py", line 65, in splice
    return v if i < 0 else v[:i] + s + v[i:]
TypeError: can only concatenate str (not "Path") to str
```

**Steps to reproduce with sample data and a .vd**
Open a file: `vd benchmark.csv`
Then: `Shift+S` `c` `source` `zy`  `o` `Ctrl-Y`

- Goto SheetsSheet
- goto source column
-  and yank the value
-   then open-file
-  use Ctrl-Y to paste
 
**Additional context**
Please include the version of VisiData. Latest develop

Bonus hidden stack trace:

On the SheetsSheet put the cursor in the `cursorDisplay` column for the SheetsSheet 
https://asciinema.org/a/LYB56EvVQLBH2RW5yCCvVp5rh

**Comment by anjakefala** [comment]
@saulpw has fixed this! =) Will be in the next patch release.
