### ISSUE TITLE
visidata fails to start with `importlib_metadata` >=5.0

### ISSUE THREAD

**Issue by datadavev** [saulpw/visidata#1552]
**Small description**
With current stable visidata, startup fails with error:
```
Traceback (most recent call last):
  File "/Users/vieglais/.virtualenvs/visidata/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/Users/vieglais/.virtualenvs/visidata/lib/python3.10/site-packages/visidata/main.py", line 350, in vd_cli
    rc = main_vd()
  File "/Users/vieglais/.virtualenvs/visidata/lib/python3.10/site-packages/visidata/main.py", line 209, in main_vd
    vd.loadConfigAndPlugins(args)
  File "/Users/vieglais/.virtualenvs/visidata/lib/python3.10/site-packages/visidata/settings.py", line 378, in loadConfigAndPlugins
    for ep in entry_points().get('visidata.plugins', []):
AttributeError: 'EntryPoints' object has no attribute 'get'
```

**Expected result**

App should start with a resource listing

**Additional context**
Pinning `importlib_metadata` to <5.0 provides an immediate fix. Longer term fix is to update `settings.py` around line 378.

**Comment by anjakefala** [comment]
Thanks for letting us know @datadavev! We have a fix ready for release soon: https://github.com/saulpw/visidata/issues/1550 That issue also contains some other workarounds that do not require you to fiddle with your environment.

If you would like a headstart on the fix, feel free to install the `develop` branch:

`pip3 install git+https://github.com/saulpw/visidata.git`
