### ISSUE TITLE
AttributeError: 'EntryPoints' object has no attribute 'get' - Ubuntu / pip installer with Python 3.10

### ISSUE THREAD

**Issue by dat-linux** [saulpw/visidata#1554]
**Small description**
Trying to run the "vd" command 

**Expected result**
The vd shell

**Actual result**
Traceback (most recent call last):
  File "/home/.cari/venv/visidata/2.10.1/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/home/.cari/venv/visidata/2.10.1/lib/python3.10/site-packages/visidata/main.py", line 350, in vd_cli
    rc = main_vd()
  File "/home/.cari/venv/visidata/2.10.1/lib/python3.10/site-packages/visidata/main.py", line 209, in main_vd
    vd.loadConfigAndPlugins(args)
  File "/home/.cari/venv/visidata/2.10.1/lib/python3.10/site-packages/visidata/settings.py", line 378, in loadConfigAndPlugins
    for ep in entry_points().get('visidata.plugins', []):
AttributeError: 'EntryPoints' object has no attribute 'get'

**Comment by anjakefala** [comment]
Thanks for letting us know! Check here for the workaround! https://github.com/saulpw/visidata/issues/1550

We will be releasing a patch release with the fix very soon. =)

**Comment by dat-linux** [comment]
That's fixed it on update, thanks.
