### ISSUE TITLE
Installing additional loader dependencies via Homebrew

### ISSUE THREAD

**Issue by Rockgecko** [saulpw/visidata#1560]
**Small description**
Unable to open a parquet file
Running in iTerm2 on MacOS Monterey 12.6
Visidata version: 2.8
(Python 3.10 installed using pyenv)
Command used:
`vd -f pandas test.parquet`

Tried also manually installing pandas using
`python -m pip install pandas`
and
`pip install pandas`
(both success with message `successfully installed pandas-1.5.0` but I still get the same error)

**Expected result**
File opens

**Actual result with screenshot**
Traceback (most recent call last):
```
  File "/opt/homebrew/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/opt/homebrew/Cellar/visidata/2.8/libexec/lib/python3.10/site-packages/visidata/main.py", line 327, in vd_cli
    rc = main_vd()
  File "/opt/homebrew/Cellar/visidata/2.8/libexec/lib/python3.10/site-packages/visidata/main.py", line 292, in main_vd
    run(vd.sheets[0])
  File "/opt/homebrew/Cellar/visidata/2.8/libexec/lib/python3.10/site-packages/visidata/vdobj.py", line 34, in _vdfunc
    return func(visidata.vd, *args, **kwargs)
  File "/opt/homebrew/Cellar/visidata/2.8/libexec/lib/python3.10/site-packages/visidata/mainloop.py", line 333, in run
    vd.push(vs)
  File "/opt/homebrew/Cellar/visidata/2.8/libexec/lib/python3.10/site-packages/visidata/sheets.py", line 1047, in push
    vs.ensureLoaded()
  File "/opt/homebrew/Cellar/visidata/2.8/libexec/lib/python3.10/site-packages/visidata/basesheet.py", line 225, in ensureLoaded
    return self.reload()   # likely launches new thread
  File "/opt/homebrew/Cellar/visidata/2.8/libexec/lib/python3.10/site-packages/visidata/loaders/_pandas.py", line 113, in reload
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

**Comment by anjakefala** [comment]
@Rockgecko Did you install VisiData originally via Homebrew?

Ah! You did!

VisiData does not come preinstalled with every dependency for every format (then there would be too many installs). When you install VisiData via Homebrew, you have to ensure the dependency is installed in the appropriate Homebrew environmment. Let me grab the syntax.

**Comment by anjakefala** [comment]
`/opt/homebrew/Cellar/visidata/2.8/libexec/bin/pip3 install pandas`

**Comment by Rockgecko** [comment]
Yes, I did install with homebrew.
`brew install saulpw/vd/visidata`

Great, I've now installed pandas (and pyarrow) using your command and this is now working, thank you for the speedy response! Sorry if this is stated somewhere in the docs - I did try to search but could not see anything.

**Comment by anjakefala** [comment]
@Rockgecko I will add it to https://github.com/visidata/homebrew-vd at least!
