### ISSUE TITLE
[unzip-http] Extract to file traces.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1567]
**Small description**
Trying to extract a file from a zip file causes it to return a traceback

**Expected result**
File extracted from zip file.

**Actual result with screenshot**
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/threads.py", line 198, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/loaders/archive.py", line 68, in extract_async
    self.zfp.extract(member=r.filename, path=path)
AttributeError: 'RemoteZipFile' object has no attribute 'extract'
```

https://asciinema.org/a/Jv7Iaw3VUE3WeyP48dkdXAQsv

**Steps to reproduce with sample data and a .vd**
Open remote zip file, try to extract file with 'x' command.  Other extract commands fail also.
```
vd https://files.digital.nhs.uk/publicationimport/pub18xxx/pub18273/nhs-staf-2015-healthcare-gp-csv.zip
```

I tried to use this, but it wouldn't even load.  It had a different stack trace:
```
vd https://raw.githubusercontent.com/saulpw/visidata/develop/sample_data/benchmark.zip
```
This might be because of limit support for ranges? Unsure.
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/threads.py", line 198, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 290, in reload
    for r in self.iterload():
  File "/usr/lib/python3.9/site-packages/visidata/loaders/archive.py", line 83, in iterload
    for zi in Progress(self.zfp.infolist()):
  File "/usr/lib/python3.9/site-packages/visidata/loaders/unzip_http.py", line 119, in infolist
    return list(self.infoiter())
  File "/usr/lib/python3.9/site-packages/visidata/loaders/unzip_http.py", line 162, in infoiter
    struct.unpack_from(self.fmt_cdirentry, resp.data, offset=filehdr_index)
struct.error: unpack_from requires a buffer of at least 65373 bytes for unpacking 46 bytes at offset 65327 (actual buffer size is 2840)
```

Open
**Additional context**
Please include the version of VisiData. Latest develop version.

**Comment by saulpw** [comment]
Okay, these work for me now!  Thanks for reporting.
