### ISSUE TITLE
[macros] General issues

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1569]
**Small description**
A couple of bugs I noted when looking at using macros:

- [x] `macro-record` record, is always recorded as the first command in the macro file. This means that if the macro is invoked, it starts capturing until stopped with `m` (at which point the user is asked to provide a command name).
- [x] Reload of `gm` sheet does not populate
- [x] [feature] Allow deletion of a macro via the `gm` sheet?
- [x] Append new lines to `macros.tsv` by default. If a user (like me 😄 ) manually edits this file but does not leave a new line at the end of the file, when a new macro is created it is appended to the end of the existing line. This error then doesn't allow vd to open next time and isn't that obvious from the trace:
```python
Traceback (most recent call last):
  File "/Users/geekscrapy/envs/py37/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/Users/geekscrapy/envs/py37/lib/python3.7/site-packages/visidata/main.py", line 354, in vd_cli
    rc = main_vd()
  File "/Users/geekscrapy/envs/py37/lib/python3.7/site-packages/visidata/main.py", line 319, in main_vd
    run(vd.sheets[0])
  File "/Users/geekscrapy/envs/py37/lib/python3.7/site-packages/visidata/vdobj.py", line 34, in _vdfunc
    return getattr(visidata.vd, func.__name__)(*args, **kwargs)
  File "/Users/geekscrapy/envs/py37/lib/python3.7/site-packages/visidata/extensible.py", line 54, in wrappedfunc
    beforefunc(*args, **kwargs)
  File "/Users/geekscrapy/envs/py37/lib/python3.7/site-packages/visidata/macros.py", line 76, in run
    vd.macrosheet
  File "/Users/geekscrapy/envs/py37/lib/python3.7/site-packages/visidata/extensible.py", line 102, in get_if_not
    setattr(self, name, func(self))
  File "/Users/geekscrapy/envs/py37/lib/python3.7/site-packages/visidata/macros.py", line 15, in macrosheet
    for ks, fn in macrosheet.rows:
ValueError: too many values to unpack (expected 2)
```

Would it be possible to also consider the following:
- [ ] Ask the user if they actually want to overwrite a current command - I was able to overwrite `type-any` and `z` as an example.
- [x] Better define how to invoke a macro, when you are asked for `save macro for keystroke:` is this a keybinding, or a `SPACE` command?

**Comment by frosencrantz** [comment]
I think this is a great set of issues and suggestions for macros.  Thanks @geekscrapy!  I want to suggest one more that this list made me think of if that is not overly rude.  I can add a separate wish-list item if that is preferable.

- [x]  The Macros sheet doesn't list the long name of the macro command.

**Comment by saulpw** [comment]
Thanks for writing this up, @geekscrapy, it was very helpful!  I put some love into the macros feature which addresses most of these, and adds some more improvements, like a help sidebar when finishing a macro.

For now, I decided not to handle confirmation for overriding a current longname or keystroke.  It's a reasonable request but more work than I'm up for at the moment.  I'm closing this issue for now, please test this new macro functionality, and if this continues to be a problem, open a new issue and we'll address it separately.
