### ISSUE TITLE
Additional "describe" aggregators cause a `KeyError`

### ISSUE THREAD

**Issue by edupont** [saulpw/visidata#1574]
**Small description**

The option to add custom aggregators, introduced by [[describe] add options.describe_aggrs #273 · saulpw/visidata@111a508](https://github.com/saulpw/visidata/commit/111a5086355d178a41c4f0e150f37c57f830f6c2), seems to have stopped working since then, causing a `KeyError`. 

Reproduction steps use the example from the mentionned commit, but I had the same issue both with library and with custom functions.

It looks like the `globals()` dictionary is losing many of its keys between the end of `.visidatarc` and the moment it reaches the `KeyError`

**Expected result**

A new column appears in the `Describe` sheet, with results form the calculation.

**Actual result with screenshot**

A new column appears with an exclamation mark `!` and the computation is aborted for the rest of the sheet.

If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.
![image](https://user-images.githubusercontent.com/5700403/198155067-7ce0cd84-a4d2-48fd-b900-5ca09825233c.png)
```
 Traceback (most recent call last):                                                            ║
   File "/usr/lib/python3.10/site-packages/visidata/threads.py", line 198, in _toplevelTryFunc ║
     t.status = func(*args, **kwargs)                                                          ║
   File "/usr/lib/python3.10/site-packages/visidata/describe.py", line 69, in reload           ║
     self.reloadColumn(srccol)                                                                 ║
   File "/usr/lib/python3.10/site-packages/visidata/describe.py", line 97, in reloadColumn     ║
     func = globals()[aggrname]                                                                ║
 KeyError: 'harmonic_mean'
 ```
 
**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

```
cat <<EOF >~/.visidatarc_with_another_name_for_your_safety
from statistics import harmonic_mean
options.describe_aggrs += ' harmonic_mean'
EOF
cat <<EOF >issue-1574.vdj
#!vd -p
{"longname": "open-file", "input": "test.tsv", "keystrokes": "o"}
{"sheet": "test", "col": "A", "row": "", "longname": "addcol-new", "input": "B", "keystrokes": "za", "comment": "append an empty column"}
{"sheet": "test", "col": "", "row": "", "longname": "add-row", "input": "", "keystrokes": "a", "comment": "append a blank row"}
{"sheet": "test", "col": "A", "row": "0", "longname": "edit-cell", "input": "1", "keystrokes": "e", "comment": "edit contents of current cell"}
{"sheet": "test", "col": "B", "row": "0", "longname": "edit-cell", "input": "2", "keystrokes": "e", "comment": "edit contents of current cell"}
{"sheet": "test", "col": "", "row": "0", "longname": "add-row", "input": "", "keystrokes": "a", "comment": "append a blank row"}
{"sheet": "test", "col": "A", "row": "1", "longname": "edit-cell", "input": "3", "keystrokes": "e", "comment": "edit contents of current cell"}
{"sheet": "test", "col": "B", "row": "1", "longname": "edit-cell", "input": "4", "keystrokes": "e", "comment": "edit contents of current cell"}
{"sheet": "test", "col": "", "row": "", "longname": "columns-sheet", "input": "", "keystrokes": "Shift+C", "comment": "open Columns Sheet: edit column properties for current sheet"}
{"sheet": "test_columns", "col": "", "row": "", "longname": "select-rows", "input": "", "keystrokes": "gs", "comment": "select all rows"}
{"sheet": "test_columns", "col": "", "row": "", "longname": "type-int-selected", "input": "", "keystrokes": "g#", "comment": "set type of selected columns to int"}
{"sheet": "test", "col": "", "row": "", "longname": "describe-sheet", "input": "", "keystrokes": "Shift+I", "comment": "open Describe Sheet with descriptive statistics for all visible columns"}
EOF

vd -p issue-1574.vdj
```

**Additional context**
Please include the version of VisiData.
```
vd --version
saul.pw/VisiData v2.10.2
```

**Comment by saulpw** [comment]
Thanks for the report, @edupont!  Should be fixed now.
