### ISSUE TITLE
[loading internal files] Stack trace on loading macros file

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1607]
**Small description**
When setting `--header` and `-d` flags Visidata crashes on reading macros file.

**Expected result**
No crash

**Actual result with screenshot**
https://asciinema.org/a/GXUDDFvxK4qmwGrHzEMiGwkFv

```
Traceback (most recent call last):
  File "/usr/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/usr/lib/python3.9/site-packages/visidata/main.py", line 354, in vd_cli
    rc = main_vd()
  File "/usr/lib/python3.9/site-packages/visidata/main.py", line 319, in main_vd
    run(vd.sheets[0])
  File "/usr/lib/python3.9/site-packages/visidata/vdobj.py", line 34, in _vdfunc
    return getattr(visidata.vd, func.__name__)(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/extensible.py", line 54, in wrappedfunc
    beforefunc(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/macros.py", line 76, in run
    vd.macrosheet
  File "/usr/lib/python3.9/site-packages/visidata/extensible.py", line 102, in get_if_not
    setattr(self, name, func(self))
  File "/usr/lib/python3.9/site-packages/visidata/macros.py", line 15, in macrosheet
    for ks, fn in macrosheet.rows:
ValueError: not enough values to unpack (expected 2, got 1)
```

**Steps to reproduce with sample data and a .vd**
- Start with a macro files.
- Run: `vd -d " " --header 0 -f tsv ../sample_data/sample.tsv`
- Crash

**Additional context**
Please include the version of VisiData. Latest develop version

This sort of issue with CLI flags interfering with loading has happened before.

**Comment by anjakefala** [comment]
This should now be fixed on `develop` branch, and will be part of the next release! Thanks for letting us know.
