### ISSUE TITLE
[graph] failure when there is only one value in the x or y column

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1673]
**Small description**
plot-column() fails when the x values are all the same, or when the y values are all the same.

**Expected result**
Some kind of plot should appear.

**Actual result with screenshot**
```
vd -p graph_one_x.vdj

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/visidata/threads.py", line 198, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/visidata/graph.py", line 74, in reload
    self.resetBounds()
  File "/usr/local/lib/python3.10/dist-packages/visidata/graph.py", line 78, in resetBounds
    super().resetBounds()
  File "/usr/local/lib/python3.10/dist-packages/visidata/canvas.py", line 489, in resetBounds
    self.visibleBox = Box(0, 0, self.plotviewBox.w/self.xScaler, self.plotviewBox.h/self.yScaler)
  File "/usr/local/lib/python3.10/dist-packages/visidata/canvas.py", line 521, in xScaler
    xratio = self.plotviewBox.w/(self.canvasBox.w*self.xzoomlevel)
ZeroDivisionError: float division by zero
```

```
vd -p graph_one_y.vdj

Traceback (most recent call last):
...
  File "/usr/local/lib/python3.10/dist-packages/visidata/canvas.py", line 489, in resetBounds
    self.visibleBox = Box(0, 0, self.plotviewBox.w/self.xScaler, self.plotviewBox.h/self.yScaler)
  File "/usr/local/lib/python3.10/dist-packages/visidata/canvas.py", line 530, in yScaler
    yratio = self.plotviewBox.h/(self.canvasBox.h*self.yzoomlevel)
ZeroDivisionError: float division by zero
```

**Steps to reproduce with sample data and a .vd**
[graph_one_x.vdj.txt](https://github.com/saulpw/visidata/files/10407511/graph_one_x.vdj.txt)
[graph_one_y.vdj.txt](https://github.com/saulpw/visidata/files/10407512/graph_one_y.vdj.txt)
[one_x_val.csv](https://github.com/saulpw/visidata/files/10407513/one_x_val.csv)
[one_y_val.csv](https://github.com/saulpw/visidata/files/10407515/one_y_val.csv)

**Additional context**
visidata-2.10.2 or latest develop branch

The problem is that self.canvasBox is created with a width or height of zero, when xmin == xmax or ymin == ymax.
https://github.com/saulpw/visidata/blob/develop/visidata/canvas.py#L485

**Comment by saulpw** [comment]
Thanks for the report, @midichef !  I have a simple fix which should at least avoid the division by zero.
