### ISSUE TITLE
[macros] error on startup if macros.tsv does not exist

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1677]
**Small description**
There is an error on startup if the file macros.tsv does not exist.

**Expected result**

**Actual result with screenshot**
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/visidata/threads.py", line 198, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/visidata/sheets.py", line 952, in reload
    self.setCols(list(self.optlines(itsource, 'header')))
  File "/usr/local/lib/python3.10/site-packages/visidata/sheets.py", line 938, in optlines
    yield next(it)
  File "/usr/local/lib/python3.10/site-packages/visidata/loaders/tsv.py", line 45, in iterload
    with self.source.open_text(encoding=self.options.encoding) as fp:
  File "/usr/local/lib/python3.10/site-packages/visidata/path.py", line 222, in open_text
    return self.open(mode=mode, encoding=encoding or vd.options.encoding, errors=vd.options.encoding_errors, newline=newline)
  File "/usr/local/lib/python3.10/site-packages/visidata/path.py", line 262, in open
    return FileProgress(path, fp=self._path.open(*args, **kwargs), **kwargs)
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/midichef/.visidata/macros.tsv'

**Steps to reproduce with sample data and a .vd**
Make sure the file macros.tsv does not exist, then run `vd`

**Additional context**
v2.11dev
The commit where this behavior begins is https://github.com/saulpw/visidata/commit/35ca095b5753120bfd20e698d91b73f73dcc174e

**Comment by anjakefala** [comment]
Ooof, that would have been a bad bug! Thank you so much @midichef! I will be sure to add tests in the CI for it, and fix it.

**Comment by anjakefala** [comment]
A fix was addressed on [v2.11](https://github.com/saulpw/visidata/issues/1677). When it is merged into `develop` (post-release), this issue will be closed.
