### ISSUE TITLE
[develop] Missing themes and features imports

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1682]
**Small description**
Unable to start vd since there are missing imports.

**Expected result**
VisiData runs

**Actual result with screenshot**
Imports are in __init__.py and are not installed when install VisiData.

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/bin/vd", line 3, in <module>
    import visidata.main
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/visidata/__init__.py", line 16[8](https://github.com/saulpw/visidata/actions/runs/3927305469/jobs/6713807144#step:6:9), in <module>
    import themes
ModuleNotFoundError: No module named 'themes'
Error: Process completed with exit code 1.
```

**Steps to reproduce with sample data and a .vd**
Install latest `develop` version, and run VisiData.  It crashes because of missing imports.

**Additional context**
Please include the version of VisiData. Latest `develop` version.

Also, this is failing in GitHub actions.

**Comment by anjakefala** [comment]
Thanks! Should fix the build.
