### ISSUE TITLE
Bug when using VisiData MySQL loader

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1744]
Operating system: Windows 7

```
Administrator@Turing MSYS ~/Desktop
$ pip install MySQLclient --upgrade
Requirement already satisfied: MySQLclient in c:\program files\python310\lib\site-packages (2.1.1)

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Administrator@Turing MSYS ~/Desktop
$ vd mysql://[rfamro@mysql-rfam-public.ebi.ac.uk:4497/Rfam](http://rfamro@mysql-rfam-public.ebi.ac.uk:4497/Rfam)
Traceback (most recent call last):
  File "C:\Program Files\Python310\Scripts\vd", line 6, in <module>
    visidata.main.vd_cli()
  File "C:\Program Files\Python310\lib\site-packages\visidata\main.py", line 354, in vd_cli
    rc = main_vd()
  File "C:\Program Files\Python310\lib\site-packages\visidata\main.py", line 319, in main_vd
    run(vd.sheets[0])
  File "C:\Program Files\Python310\lib\site-packages\visidata\vdobj.py", line 34, in _vdfunc
    return getattr(visidata.vd, func.__name__)(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\visidata\extensible.py", line 55, in wrappedfunc
    return oldfunc(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\visidata\mainloop.py", line 377, in run
    ret = vd.mainloop(scr)
  File "C:\Program Files\Python310\lib\site-packages\visidata\mainloop.py", line 240, in mainloop
    self.draw_all()
  File "C:\Program Files\Python310\lib\site-packages\visidata\mainloop.py", line 144, in draw_all
    vd.draw_sheet(vd.win1, ss1[0])
  File "C:\Program Files\Python310\lib\site-packages\visidata\mainloop.py", line 33, in draw_sheet
    sheet.ensureLoaded()
  File "C:\Program Files\Python310\lib\site-packages\visidata\basesheet.py", line 245, in ensureLoaded
    return self.reload()   # likely launches new thread
  File "C:\Program Files\Python310\lib\site-packages\visidata\loaders\mysql.py", line 98, in reload
    with self.sql.cur(qstr) as cur:
  File "C:\Program Files\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Program Files\Python310\lib\site-packages\visidata\loaders\mysql.py", line 39, in cur
    connection = mysql.connect(
  File "C:\Program Files\Python310\lib\site-packages\MySQLdb\__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\MySQLdb\connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
TypeError: connect() argument 3 must be str, not None
```

**Comment by saulpw** [comment]
Hi @cool-RR, the mysql loader was put together by @p3k and and @SuRaMoN.  If they'd be up for debugging this, that would definitely merit a VisiData contributor sticker!  It looks like something weird though, as argument 3 appears to be the 'host', so I don't know why it would be `None`.

Otherwise, for databases we're moving towards vdsql for more official support.  Does vdsql work with this mysql database?

**Comment by cool-RR** [comment]
> Does vdsql work with this mysql database?

Haven't tried it, that's less interesting to me.
