### ISSUE TITLE
[gzd] Cell delete on calculated column throws error

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1764]
**Small description**
When creating a column from `=` you cannot delete a cell value and the following "odd" error is set in the status bar.

`[4x] 1 calced 1 not None`

**Expected result**
To be able to delete the cell values

**Actual result with screenshot**
```
Traceback (most recent call last):
  File "/Users/geekscrapy/python37/lib/python3.7/site-packages/visidata/column.py", line 405, in setValueSafe
    return self.setValue(row, value)
  File "/Users/geekscrapy/python37/lib/python3.7/site-packages/visidata/column.py", line 399, in setValue
    self.putValue(row, val)
  File "/Users/geekscrapy/python37/lib/python3.7/site-packages/visidata/column.py", line 392, in putValue
    return self.setter(self, row, val)
  File "/Users/geekscrapy/python37/lib/python3.7/site-packages/visidata/shell.py", line 94, in <lambda>
    setter=lambda col,row,val: os.truncate(row, int(val))),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Steps to reproduce with sample data and a .vd**
```bash
# touch 1 2 3
# vd .
```

```vdj
#!vd -p
{"longname": "open-file", "input": ".", "keystrokes": "o"}
{"sheet": "", "col": "modtime", "row": "", "longname": "addcol-expr", "input": "1", "keystrokes": "=", "comment": "create new column from Python expression, with column names as variables"}
{"sheet": "", "col": "", "row": "\u30ad.,3", "longname": "stoggle-row", "input": "", "keystrokes": "t", "comment": "toggle selection of current row"}
{"sheet": "", "col": "", "row": "\u30ad.,2", "longname": "stoggle-row", "input": "", "keystrokes": "t", "comment": "toggle selection of current row"}
{"sheet": "", "col": "1", "row": "", "longname": "delete-cells", "input": "", "keystrokes": "gzd", "comment": "delete contents of current column for selected rows (set to None)"}
```

**Comment by geekscrapy** [comment]
FWIW, freezing the new column and then doing the `gzd` works as expected.

**Comment by saulpw** [comment]
Yeah we need to get a better error message.  How about:

```
Cannot change value of calculated column.  Use `'` to freeze column.
```

**Comment by geekscrapy** [comment]
Yup! logical to me!

**Comment by anjakefala** [comment]
@geekscrapy I improved the error message! Please note that it is a known issue that the colouring of the status is kinda funky. That is in the queue to fix. =)
