### ISSUE TITLE
in json, {sheet.cursorColIndex} will trigger ValueError: None is not in list

### ISSUE THREAD

**Issue by Freed-Wu** [saulpw/visidata#1803]
**Steps to reproduce with sample data and a .vd**

`a.json`:

```json
[{"a": 1, "b": 1}]
```

then set `options.disp_rstatus_fmt = "{sheet.cursorColIndex}"` in config file

```
vd a.json
```

**Actual result with screenshot**
```
Traceback (most recent call last):
  File "/usr/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/usr/lib/python3.10/site-packages/visidata/main.py", line 354, in vd_cli
    rc = main_vd()
  File "/usr/lib/python3.10/site-packages/visidata/main.py", line 319, in main_vd
    run(vd.sheets[0])
  File "/usr/lib/python3.10/site-packages/visidata/vdobj.py", line 34, in _vdfunc
    return getattr(visidata.vd, func.__name__)(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/visidata/extensible.py", line 55, in wrappedfunc
    return oldfunc(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/visidata/mainloop.py", line 377, in run
    ret = vd.mainloop(scr)
  File "/usr/lib/python3.10/site-packages/visidata/mainloop.py", line 240, in mainloop
    self.draw_all()
  File "/usr/lib/python3.10/site-packages/visidata/mainloop.py", line 144, in draw_all
    vd.draw_sheet(vd.win1, ss1[0])
  File "/usr/lib/python3.10/site-packages/visidata/mainloop.py", line 41, in draw_sheet
    self.drawRightStatus(scr, sheet)  # visible during this getkeystroke
  File "/usr/lib/python3.10/site-packages/visidata/statusbar.py", line 174, in drawRightStatus
    (vd.rightStatus(vs), 'color_status'),
  File "/usr/lib/python3.10/site-packages/visidata/statusbar.py", line 164, in rightStatus
    return MissingAttrFormatter().format(sheet.options.disp_rstatus_fmt, sheet=sheet, vd=vd)
  File "/usr/lib/python3.10/string.py", line 161, in format
    return self.vformat(format_string, args, kwargs)
  File "/usr/lib/python3.10/string.py", line 165, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/usr/lib/python3.10/string.py", line 205, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "/usr/lib/python3.10/site-packages/visidata/utils.py", line 118, in get_field
    return super().get_field(field_name, *args, **kwargs)
  File "/usr/lib/python3.10/string.py", line 276, in get_field
    obj = getattr(obj, i)
  File "/usr/lib/python3.10/site-packages/visidata/sheets.py", line 433, in cursorColIndex
    return self.columns.index(self.cursorCol)
ValueError: None is not in list
```
**Expected result**

No error

**Small description**
It only occur when

1. `{sheet.cursorColIndex}`
2. must be a json. tsv will not trigger.

**Comment by anjakefala** [comment]
This seems to be fixed @Freed-Wu!
