### ISSUE TITLE
Vdsql was unable to open a `.db` file

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#1864]
```
vdsql --sqlite foo.db
Traceback (most recent call last):
  File "/usr/local/bin/vdsql", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/vdsql/__main__.py", line 19, in main
    main.vd_cli()
  File "/usr/local/lib/python3.9/site-packages/visidata/main.py", line 354, in vd_cli
    rc = main_vd()
  File "/usr/local/lib/python3.9/site-packages/visidata/main.py", line 244, in main_vd
    vs = vd.openSource(p, create=True, **opts) or vd.fail(f'could not open {p}')
  File "/usr/local/lib/python3.9/site-packages/visidata/_open.py", line 99, in openSource
    vs = vd.openPath(Path(p), filetype=filetype, create=create)  # convert to Path and recurse
  File "/usr/local/lib/python3.9/site-packages/visidata/_open.py", line 82, in openPath
    return openfunc(p)
  File "/usr/local/lib/python3.9/site-packages/vdsql/_ibis.py", line 73, in open_vdsql
    vd.configure_ibis()
  File "/usr/local/lib/python3.9/site-packages/vdsql/_ibis.py", line 53, in configure_ibis
    ibis.options.verbose_log = vd.status
AttributeError: module 'ibis' has no attribute 'options'
```

Ibis 3.2.0

**Comment by saulpw** [comment]
Hm, this is very weird. What's up with the `--sqlite` option, though?  That shouldn't do anything..

**Comment by joegrover** [comment]
I'm bumping into the same issue (but without the `--sqlite`). Everything works fine if I rename the file to be a `file.sqlite`, but it just isn't recognizing `.db` as a sqlite file the way that `vd` does and I can't figure out how to tell `vdsql` that the file is a sqlite db.

EDIT:
Well, I'm getting _mostly_ the same issue. My error message is

    AttributeError: module 'ibis' has no attribute 'db'

But I'm guessing that's what @anjakefala had initially as well, and then tried with `--sqlite` to goose `vdsql` to read the file as SQLite

**Comment by anjakefala** [comment]
Hi @joegrover!

The `.db` extension is actually only supported by the unreleased version of Ibis.

You would need to do `pip3 install git+https://github.com/ibis-project/ibis.git`.

And then use `-f ibis`. This stacktrace was some other very weird thing that I have not since reproduced.
