### ISSUE TITLE
bigquery - AttributeError: 'IbisTableIndexSheet' object has no attribute 'sheet_type'

### ISSUE THREAD

**Issue by lakaiii** [saulpw/visidata#1865]
visidata v2.10.2 

python 3.8.12

```
>>> ibis.__version__
'3.2.0'

>>> import ibis_bigquery
>>> ibis_bigquery.__version__
'2.2.0'

```
How to reproduce:

1. open `vdsql bigquery://bigquery-public-data`

2. select first dataset `america_health_rankings` by hitting "Enter"

second, third, fourth dataset also did not work for me
-> 

AttributeError: 'IbisTableIndexSheet' object has no attribute 'sheet_type'

**Comment by anjakefala** [comment]
I appreciate you filing an issue!

Could you paste the full stacktrace?

**Comment by lakaiii** [comment]
Of course, sorry I was not aware that I could access the stacktrace in Visidata. But of course it's possible. Great tool!

```
 Traceback (most recent call last):
  File "/home/martin/.local/pipx/venvs/visidata/lib/python3.8/site-packages/visidata/threads.py", line 198, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/home/martin/.local/pipx/venvs/visidata/lib/python3.8/site-packages/visidata/sheets.py", line 290, in reload
    for r in self.iterload():
  File "/home/martin/.local/pipx/venvs/visidata/lib/python3.8/site-packages/vdsql/_ibis.py", line 133, in iterload
    yield self.sheet_type(tblname,
AttributeError: 'IbisTableIndexSheet' object has no attribute 'sheet_type'
```

**Comment by saulpw** [comment]
Thanks @lakaiii !  Should be fixed now.

**Comment by lakaiii** [comment]
That was quick.

**Comment by lakaiii** [comment]
May not have fixed it - but I can wait ;-) 

took the following steps:

 1. Installed vdsql from git to point at `vdsql @ git+https://github.com/visidata/vdsql.git@257336271b3e9b0fdefc3e32bd7b1cb296e2fc62`
  


2.    open vdsql bigquery://bigquery-public-data ##  (two slashes before the project name - is that OK? I saw three elswhere)

3.  select first dataset america_health_rankings by hitting "Enter"




Traceback below

  ```
  Traceback (most recent call last):
  File "/home/martin/.local/pipx/venvs/visidata/lib/python3.8/site-packages/visidata/threads.py", line 198, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/home/martin/.local/pipx/venvs/visidata/lib/python3.8/site-packages/visidata/sheets.py", line 290, in reload
    for r in self.iterload():
  File "/home/martin/.local/pipx/venvs/visidata/lib/python3.8/site-packages/vdsql/_ibis.py", line 118, in iterload
    with self.con as con:
  File "/home/martin/.pyenv/versions/3.8.12/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/martin/.local/pipx/venvs/visidata/lib/python3.8/site-packages/vdsql/_ibis.py", line 90, in get_conn
    r = ibis.connect(str(self.source))
  File "/home/martin/.pyenv/versions/3.8.12/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/martin/.local/pipx/venvs/visidata/lib/python3.8/site-packages/ibis/backends/base/__init__.py", line 788, in _
    return _connect(url, **kwargs)
  File "/home/martin/.local/pipx/venvs/visidata/lib/python3.8/site-packages/ibis/common/dispatch.py", line 104, in __call__
    return func(s, *args, **kwargs, **match.groupdict())
  File "/home/martin/.local/pipx/venvs/visidata/lib/python3.8/site-packages/ibis/backends/base/__init__.py", line 726, in _
    return instance._from_url(url)
  File "/home/martin/.local/pipx/venvs/visidata/lib/python3.8/site-packages/ibis/backends/base/sql/__init__.py", line 61, in _from_url
    return self.connect(**kwargs)
TypeError: connect() got an unexpected keyword argument 'host'
```

**Comment by lxcode** [comment]
Yeah, i have the same issue with vdsql from git — in the pip version, I got 

```AttributeError: 'IbisTableIndexSheet' object has no attribute 'sheet_type'``` 

in the git version I get the same ```TypeError: connect() got an unexpected keyword argument 'host'``` 

with similar stack trace except with python3.9 on macOS.

(update -- tried a fresh python 3.8, same issue)

**Comment by HerveMignot** [comment]
Changing back line 133 in _ibis.py from:
```
yield self.sheet_type(tblname,
```
to 
```
yield IbisTableSheet(tblname,
```

removes the error and seems to work down the line.
This was changed in commit `c217ca9` (refactoring).

**Comment by saulpw** [comment]
I updated the vdsql bigquery sheet to use the more general `ibis.connect()` interface to create the connection for bigquery, which now should be able to just take a bigquery URL:

```
vdsql bigquery://<billing_project>/<project_id>
```
For instance, to use the bigquery-public-data project, I created a billing project named visidata, and had to access it like:
```
vdsql bigquery://visidata/bigquery-public-data
```
Otherwise, without the billing project, you'll be able to list the datasets, but not actually launch any "jobs" to access the data. But this seems to work cleanly now!
