### ISSUE TITLE
[scroll-cells-*] When column is offscreen error is thrown

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1908]
**Small description**
when using a `scroll-cells-*` command and the column is out of view, the following error is shown:

```
Traceback (most recent call last):
  File "/Users/geekscrapy/.miniconda3/envs/py37/lib/python3.7/site-packages/visidata/basesheet.py", line 200, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/Users/geekscrapy/.miniconda3/envs/py37/lib/python3.7/site-packages/visidata/basesheet.py", line 73, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "scroll-cells-rightmost", line 1, in <module>
    import plugins.agg_stdev
  File "/Users/geekscrapy/.miniconda3/envs/py37/lib/python3.7/site-packages/visidata/extensible.py", line 92, in dofunc
    return func(self)
  File "/Users/geekscrapy/.miniconda3/envs/py37/lib/python3.7/site-packages/visidata/movement.py", line 99, in visibleWidth
    return self.sheet._visibleColLayout[vcolidx][1]
KeyError: 1
```

**Expected result**
Not throw an error.

**Steps to reproduce with sample data and a .vd**
Create a keycol which has a width larger than the screen width
Move the cursor to another column offscreen
Use one of the scroll-cells-*` commands

**Additional context**
- VisiData v2.12dev
- Python 3.7.13

**Comment by saulpw** [comment]
Thanks for the report, @geekscrapy.  Should be fixed now.
