### ISSUE TITLE
How do I use vdsql with ibis?

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#1929]
### Discussed in https://github.com/saulpw/visidata/discussions/1928

<div type='discussions-op-text'>

<sup>Originally posted by @dufferzafar June 19, 2023</sup>
I have `ibis-framework[mysql]` installed, but when I use `vdsql 'mysql://DSN'` vd tries to go through the standard mysql loader. How do I prevent that from happening & use the `ibis` loader?

Traceback:

```python

saul.pw/VisiData v2.12dev
Traceback (most recent call last):
  File "/home/dufferzafar/.local/bin/vdsql", line 8, in <module>
    rc = main()
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/visidata/apps/vdsql/__main__.py", line 19, in main
    main.vd_cli()
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/visidata/main.py", line 372, in vd_cli
    rc = main_vd()
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/visidata/main.py", line 333, in main_vd
    run(vd.sheets[0])
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/visidata/vdobj.py", line 33, in _vdfunc
    return getattr(visidata.vd, func.__name__)(*args, **kwargs)
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/visidata/extensible.py", line 57, in wrappedfunc
    return oldfunc(*args, **kwargs)
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/visidata/extensible.py", line 57, in wrappedfunc
    return oldfunc(*args, **kwargs)
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/visidata/mainloop.py", line 288, in run
    ret = vd.mainloop(scr)
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/visidata/mainloop.py", line 181, in mainloop
    self.draw_all()
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/visidata/mainloop.py", line 115, in draw_all
    vd.drawSheet(vd.win1, ss1[0])
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/visidata/mainloop.py", line 29, in drawSheet
    sheet.ensureLoaded()
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/visidata/basesheet.py", line 258, in ensureLoaded
    return self.reload()   # likely launches new thread
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/visidata/loaders/mysql.py", line 99, in reload
    with self.sql.cur(qstr) as cur:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/visidata/loaders/mysql.py", line 36, in cur
    import MySQLdb as mysql
ModuleNotFoundError: No module named 'MySQLdb'

```</div>

**Comment by dufferzafar** [comment]
Thanks @anjakefala, I wasn't sure if this was an issue with my setup or vd itself.

Do let me know if you require any more info.

I think the issue could be here:

https://github.com/saulpw/visidata/blob/b401b3416d31016b67062ceb7b3896a2e88f6272/visidata/apps/vdsql/__main__.py#L14-L17

setattr isn't called because there's already a `openurl_mysql` from the normal loaders?

We seem to be using ibis for DBs that we don't already have a support for!?

**Comment by dufferzafar** [comment]
I removed the hasattr check & vd started using the ibis loaders!

Another snafu though!

My server is MySQL v5.1 (quite old, I know) so I got `OperationalError: (pymysql.err.OperationalError) (1115, "Unknown character set: 'utf8mb4'")`

Tried passing in `?charset=utf8` as specified here: https://stackoverflow.com/a/11083221

But that fails too: `TypeError: do_connect() got an unexpected keyword argument 'charset'`

**Comment by dufferzafar** [comment]
I moved on to trying a postgresql database, which works! 🎉 

But, we need to use `postgres://` scheme rather than `postgresql://` (since that is what ibis uses)

`vdsql` is able to load data, but it is VERY SLOW!

I used to feel that the builtin `postgresql` loader was slow, but it's much faster as compared to `ibis`. I also used to like the `est_rows` in there which starts filled, but the ibis sheet only shows rows that are actually loaded.

This will probably be another issue I guess. I'll look into some ibis internals and see what can be improved.

**Comment by saulpw** [comment]
> setattr isn't called because there's already a openurl_mysql from the normal loaders

The intent was to have vdsql provide its loader for dbs without a builtin implementation, but leave the builtin loaders since they may be more functional (allowing e.g. edit/commit, rowcount estimates, etc).  Then the vdsql loader could be invoked for any DB URL with `-f vdsql`.  But you're right, this is in `vdsql.main()`, which should only be called if `vdsql` is run directly (and not via `vd`), in which case we do want to always use the vdsql implementation.

**Comment by saulpw** [comment]
Hi @dufferzafar, passing `charset` as a parameter to mysql engine should hopefully be available with the next version of ibis, as per the PR above.  Also I'm not sure why the postgres loader would be slow; the query itself should be fast and it should only be loading 500 rows.  If this is still bothering you, please file another issue for that specifically.

As for the rowcount estimates, I agree!  But it's quite time-consuming to count the number of rows in a large dataset (it requires a full table scan, much to my dismay).  So there is `options.sql_always_count` which defaults to False, but which you can set to True if you want the count.
