### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by snooppr** [saulpw/visidata#1939]
`$ vd https://forumkinopoisk.ru/`
or
`$ vd https://x-waters.com/events/murom/participants-murom/`

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/data/data/com.termux/files/usr/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='x-waters.com', port=443): Max retries exceeded with url: /events/murom/participants-murom/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/visidata/main.py", line 354, in vd_cli
    rc = main_vd()
         ^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/visidata/main.py", line 244, in main_vd
    vs = vd.openSource(p, create=True, **opts) or vd.fail(f'could not open {p}')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/visidata/_open.py", line 95, in openSource
    vs = vd.openPath(Path(p), filetype=filetype)  # convert to Path and recurse
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/visidata/_open.py", line 50, in openPath
    return openfunc(p, filetype=filetype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/visidata/loaders/http.py", line 23, in openurl_http
    response = requests.get(path.given, stream=True, **vd.options.getall('http_req_'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='x-waters.com', port=443): Max retries exceeded with url: /events/murom/participants-murom/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))

You get the same error through the "requests" library request.  The solution is to disable certificate verification and warnings (verify=False).
-------

```
$ python

import requests
requests.packages.urllib3.disable_warnings()
r=requests.get("https://x-waters.com/events/murom/", verify=False)
r.text
```
good

**Comment by anjakefala** [comment]
Support got added for disabling SSL verification on the `develop` branch: https://github.com/saulpw/visidata/issues/1839 =)

**Comment by saulpw** [comment]
To copy from that thread: use `--http_req_verify=0`

**Comment by snooppr** [comment]
> @saulpw 
`$ pip list | grep visid`
2.11

_Interestingly, the `vd --version` flag does not exist._

`vd --http_req_verify=0 https://x-waters.com/events/murom/participants-murom/`

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/visidata/main.py", line 354, in vd_cli
    rc = main_vd()
         ^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/visidata/main.py", line 244, in main_vd
    vs = vd.openSource(p, create=True, **opts) or vd.fail(f'could not open {p}')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/visidata/_open.py", line 95, in openSource
    vs = vd.openPath(Path(p), filetype=filetype)  # convert to Path and recurse
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/visidata/_open.py", line 50, in openPath
    return openfunc(p, filetype=filetype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/visidata/loaders/http.py", line 23, in openurl_http
    response = requests.get(path.given, stream=True, **vd.options.getall('http_req_'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/adapters.py", line 460, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/adapters.py", line 263, in cert_verify
    raise OSError(
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: 0

**Comment by anjakefala** [comment]
@saulpw I just noticed that `urllib.request.Request` does not support the `verify` parameter: https://docs.python.org/3/library/urllib.request.html#urllib.request.Request

That was from `requests.request`: https://requests.readthedocs.io/en/latest/api/?highlight=verify#requests.request. We need to look into what the equivalent for urllib.request.Request is.

**Comment by anjakefala** [comment]
For urllib.request.Request it seems we would need to create and pass a context variable: https://stackoverflow.com/questions/36600583/python-3-urllib-ignore-ssl-certificate-verification

**Comment by snooppr** [comment]
$ python
```
import ssl
import urllib.request

ssl._create_default_https_context = ssl._create_unverified_context
r = urllib.request.Request("https://x-waters.com/events/murom/participants-murom/")
with urllib.request.urlopen(r) as res:
    print(res.status)
```
ok, 200.

**Comment by saulpw** [comment]
Okay I added an `http_ssl_verify` option (in develop) to use instead.

**Comment by anjakefala** [comment]
It can be used like: `vd --http-ssl-verify=False https://x-waters.com/events/murom/participants-murom/ `

or by setting `options.http_ssl_verify=False` in your `~/.visidatarc`. With that one, SSL verification would be turned off for every request.

**Comment by aborruso** [comment]
Hi @anjakefala and @saulpw , I have saul.pw/VisiData v3.0.2, on Debian 12.

If I run

```
vd --http_req_verify=False -f html "https://cercalatuascuola.istruzione.it/cercalatuascuola/ricerca/risultati?codiceRegione=LI_LIGURIA&codiceProvincia=GE_GENOVA&codiceComune=D969_GENOVA&codiceOrdine=4&checkStatale=S&checkNonStatale=S&codiceTipologiaStataleNuovoOrdinamento=&radioBiennioTriennio=Biennio&denominazione=&codMecc=&tipoRicerca=AVANZATA&gidf=1"
```

I have this error

```
setting unknown option http_req_verify
Traceback (most recent call last):
  File "/home/aborruso/.local/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/home/aborruso/.local/lib/python3.11/site-packages/visidata/main.py", line 381, in vd_cli
I shall never get to twenty at that rate!
    rc = main_vd()
         ^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/visidata/main.py", line 303, in main_vd
    vs = vd.openSource(p, create=True, **opts) or vd.fail(f'could not open {p}')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/visidata/_open.py", line 155, in openSource
    vs = vd.openPath(Path(p), filetype=filetype)  # convert to Path and recurse
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/visidata/_open.py", line 91, in openPath
    return openfunc(p, filetype=filetype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/visidata/loaders/http.py", line 51, in openurl_http
    req = urllib.request.Request(path.given, **vd.options.getall('http_req_'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Request.__init__() got an unexpected keyword argument 'verify'
```

How to use properly `--http_req_verify`.

Thank you

**Comment by saulpw** [comment]
Hi @aborruso, the option is `http_ssl_verify` now.

**Comment by aborruso** [comment]
> Hi @aborruso, the option is `http_ssl_verify` now.

If I use it, I have

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.11/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aborruso/.local/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/home/aborruso/.local/lib/python3.11/site-packages/visidata/main.py", line 381, in vd_cli
    rc = main_vd()
         ^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/visidata/main.py", line 303, in main_vd
    vs = vd.openSource(p, create=True, **opts) or vd.fail(f'could not open {p}')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/visidata/_open.py", line 155, in openSource
    vs = vd.openPath(Path(p), filetype=filetype)  # convert to Path and recurse
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/visidata/_open.py", line 91, in openPath
    return openfunc(p, filetype=filetype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/visidata/loaders/http.py", line 52, in openurl_http
    response = urllib.request.urlopen(req, context=ctx)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:992)>
```

**Comment by aborruso** [comment]
@saulpw Do you have any advice for me? What can I do to solve this error?

Thank you

**Comment by saulpw** [comment]
ChatGPT says:

> This SSL error occurs when an attempt is made to use SSL/TLS renegotiation, which is considered insecure and has been disabled in modern OpenSSL versions. To solve this, you should ensure both your client and server are using up-to-date SSL/TLS protocols (e.g., TLSv1.2 or TLSv1.3) and configurations that do not rely on legacy renegotiation.
>
> If you have control over the server, update its configuration to disable SSL renegotiation. If you're working on the client side and need a quick fix, verify that you're using a recent version of the OpenSSL library and your Python requests or urllib3 packages are up to date. However, be aware that enabling unsafe renegotiation is not recommended due to security vulnerabilities.

I don't have any other advice, sorry :(
