### ISSUE TITLE
[input/help] Stack trace when trying to use help from input

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1994]
**Small description**

Stack trace when trying to use help from input

**Expected result**
No stack trace, help shown.

**Actual result with screenshot**

https://asciinema.org/a/JtJa4HyNEEtHwGeWnJegy5P4d

When typing Ctrl-G in the input box.

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 200, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 73, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "edit-cell", line 1, in <module>
    'VisiData: a curses interface for exploring and arranging tabular data'
  File "/usr/lib/python3.9/site-packages/visidata/_input.py", line 530, in editCell
    r = vd.editText(y, x, w, attr=colors.color_edit_cell, **editargs)
  File "/usr/lib/python3.9/site-packages/visidata/_input.py", line 319, in editText
    v = vd.editline(vd.activeSheet._scr, y, x, w, display=display, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/_input.py", line 232, in editline
    vd.getHelpPane('input', module=__name__).draw(scr, y=y)
  File "/usr/lib/python3.9/site-packages/visidata/help.py", line 124, in getHelpPane
    ret.amgr.load(name, (vd.pkg_resources_files(module)/f'ddw/{name}.ddw').open(encoding='utf-8'))
  File "/usr/lib/python3.9/site-packages/visidata/path.py", line 25, in pkg_resources_files
    return files(package)
  File "/usr/lib/python3.9/importlib/resources.py", line 147, in files
    return _common.from_package(_get_package(package))
  File "/usr/lib/python3.9/importlib/resources.py", line 51, in _get_package
    raise TypeError('{!r} is not a package'.format(package))
TypeError: 'visidata._input' is not a package
```
https://asciinema.org/a/JtJa4HyNEEtHwGeWnJegy5P4d

**Steps to reproduce with sample data and a .vd**
Type  Ctrl-G when entering input.

**Additional context**
Please include the version of VisiData and Python.
Latest Develop Python 3.9.2

**Comment by frosencrantz** [comment]
This could be related to the issue https://github.com/saulpw/visidata/issues/1971

**Comment by saulpw** [comment]
Thanks for reporting, @frosencrantz !  Should be fixed now.

**Comment by frosencrantz** [comment]
Awesome, @saulpw!  It works now.
