### ISSUE TITLE
[pyobj-cell] Stack traces when diving into a cell `zCtrl+Y`

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2001]
**Small description**
Stack traces when diving into a cell `zCtrl+Y`

**Expected result**
No stack trace.

**Actual result with screenshot**

https://asciinema.org/a/PcnS2PDJ4RoqcZ83u2EGvJ402

```Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 200, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 73, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "pyobj-cell", line 1, in <module>
    'VisiData: a curses interface for exploring and arranging tabular data'
  File "/usr/lib/python3.9/site-packages/visidata/pyobj.py", line 399, in openCellPyobj
    return PyobjSheet(name, source=col.getValue(row))
NameError: name 'row' is not defined
```

**Steps to reproduce with sample data and a .vd**

`vd sample_data/benchmark.jsonl`

Type `zCtrl+Y`  on the Customer cell that is a list (first row).

**Additional context**
Please include the version of VisiData and Python.  Using the latest develop version with Python 3.9.2

There was a  recent change to fix (https://github.com/saulpw/visidata/commit/390a45713c12a08af5194bff17159bbf11c72ba6) this code:

https://github.com/saulpw/visidata/blob/develop/visidata/pyobj.py#L395-L399

**Comment by frosencrantz** [comment]
Thank you @saulpw!  That was fast! 🚀
