### ISSUE TITLE
Bug: cannot read .vds with expression column

### ISSUE THREAD

**Issue by pacien** [saulpw/visidata#2035]
**Small description**

Visidata cannot read back sheet(s) it saved as `.vds` if they contain an
expression column.

"KeyError: 'ExprColumn'" shows as error, resulting in a partial read.

**Expected result**

It should be able to read those files.

**Actual result with ~~screenshot~~ stacktrace**

```
Traceback (most recent call last):
  File "/nix/store/z4xjb4j8i73894r2wqjvlnps9j60rjr0-visidata-2.11/lib/python3.10/site-packages/visidata/threads.py", line 198, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/nix/store/z4xjb4j8i73894r2wqjvlnps9j60rjr0-visidata-2.11/lib/python3.10/site-packages/visidata/pyobj.py", line 26, in reload
    for r in self.iterload():
  File "/nix/store/z4xjb4j8i73894r2wqjvlnps9j60rjr0-visidata-2.11/lib/python3.10/site-packages/visidata/loaders/vds.py", line 76, in iterload
    c = globals()[classname](d.pop('name'), sheet=self)
KeyError: 'ExprColumn'
```

**Steps to reproduce with sample data and a .vd**

Create and save some test sheet with an expr column with this `cmdlog.vdj`:

```
#!vd -p
{"col": "", "row": "", "longname": "open-new", "input": "", "keystrokes": "Shift+A", "comment": "Open new empty sheet"}
{"sheet": "unnamed", "col": "A", "row": "", "longname": "type-int", "input": "", "keystrokes": "#", "comment": "set type of current column to int"}
{"sheet": "unnamed", "col": "", "row": "", "longname": "add-row", "input": "", "keystrokes": "a", "comment": "append a blank row"}
{"sheet": "unnamed", "col": "A", "row": "0", "longname": "edit-cell", "input": "2", "keystrokes": "e", "comment": "edit contents of current cell"}
{"sheet": "unnamed", "col": "A", "row": "", "longname": "addcol-expr", "input": "A*2", "keystrokes": "=", "comment": "create new column from Python expression, with column names as variables"}
{"sheet": "unnamed", "col": "", "row": "", "longname": "save-sheet", "input": "sheet.vds", "keystrokes": "Ctrl+S", "comment": "save current sheet to filename in format determined by extension (default .tsv)"}
```

This produces `sheet.vds` as follows, which seems valid:

```
#{"name": "unnamed"}
#{"name": "A", "width": 4, "height": 1, "expr": null, "keycol": 0, "formatter": "", "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "int", "col": "Column"}
#{"name": "A*2", "width": 5, "height": 1, "expr": "A*2", "keycol": 0, "formatter": "", "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "", "col": "ExprColumn"}
{"A": 2, "A*2": 4}
```

Quit visidata and open that file again with `vd sheet.vds`,
and observe the loading error.

**Additional context**

- visidata v2.11
- python 3.10.12

**Comment by saulpw** [comment]
Thanks @pacien!  Sorry for the oversight in the first place.
