### ISSUE TITLE
--encoding-errors seemingly ignored when input  comes from stdin

### ISSUE THREAD

**Issue by stephane-chazelas** [saulpw/visidata#2047]
**Description**

```
printf '"%s"\n' header $'\xe9' | vd --encoding=utf-8 --encoding-errors=surrogateescape -f csv
```

(those `--encoding=utf-8 --encoding-errors=surrogateescape` also being  meant to be the default) fails with:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 10: invalid continuation byte
```

So with decoding errors handled as if `--encoding-errors` was set to `strict`.

```
vd -f csv <(printf '"%s"\n' header $'\xe9')
```

(here from a shell  with Korn-style process substitution such as zsh or bash) is fine.

Same happens with JSON or tsv...

Full trace with `^E`:

```
 Traceback (most recent call last):                                                                 ║
   File "/usr/lib/python3/dist-packages/visidata/threads.py", line 198, in _toplevelTryFunc         ║
     t.status = func(*args, **kwargs)                                                               ║
                ^^^^^^^^^^^^^^^^^^^^^                                                               ║
   File "/usr/lib/python3/dist-packages/visidata/sheets.py", line 952, in reload                    ║
     self.setCols(list(self.optlines(itsource, 'header')))                                          ║
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                           ║
   File "/usr/lib/python3/dist-packages/visidata/sheets.py", line 938, in optlines                  ║
     yield next(it)                                                                                 ║
           ^^^^^^^^                                                                                 ║
   File "/usr/lib/python3/dist-packages/visidata/loaders/csv.py", line 39, in iterload              ║
     yield next(rdr)                                                                                ║
           ^^^^^^^^^                                                                                ║
   File "/usr/lib/python3/dist-packages/visidata/path.py", line 393, in __next__                    ║
     r = next(self.rf.iter_lines)                                                                   ║
         ^^^^^^^^^^^^^^^^^^^^^^^^                                                                   ║
   File "<frozen codecs>", line 322, in decode                                                      ║
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 10: invalid continuation byte ║
```

For comparison, here's the trace for:

```
vd -f csv --encoding-errors=strict <(printf '"%s"\n' header $'\xe9')
```

```
 Traceback (most recent call last):                                                                 ║
   File "/usr/lib/python3/dist-packages/visidata/threads.py", line 198, in _toplevelTryFunc         ║
     t.status = func(*args, **kwargs)                                                               ║
                ^^^^^^^^^^^^^^^^^^^^^                                                               ║
   File "/usr/lib/python3/dist-packages/visidata/sheets.py", line 952, in reload                    ║
     self.setCols(list(self.optlines(itsource, 'header')))                                          ║
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                           ║
   File "/usr/lib/python3/dist-packages/visidata/sheets.py", line 938, in optlines                  ║
     yield next(it)                                                                                 ║
           ^^^^^^^^                                                                                 ║
   File "/usr/lib/python3/dist-packages/visidata/loaders/csv.py", line 39, in iterload              ║
     yield next(rdr)                                                                                ║
           ^^^^^^^^^                                                                                ║
   File "/usr/lib/python3/dist-packages/visidata/path.py", line 115, in __iter__                    ║
     for line in self.fp:                                                                           ║
   File "<frozen codecs>", line 322, in decode                                                      ║
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 10: invalid continuation byte ║
```

Older versions (2.2.1 on Ubuntu 22.04 for  instance) also seemed to ignore `--encoding`.

**Additional context**

```
$ python3 --version
Python 3.11.5
$ vd --version
saul.pw/VisiData v2.11
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux trixie/sid
Release:        n/a
Codename:       trixie
```

**Comment by stephane-chazelas** [comment]
Note that #2047 and #2048 were found while working on https://unix.stackexchange.com/questions/757832/how-to-process-json-with-strings-containing-invalid-utf-8/758016#758016

`vd -f json <(cmd)` in place of `cmd | vd -f json` is a way to work  around #2047 and `cmd | vd -f json` in place of `vd -f json <(cmd)` is a way  to work around #2048 so it's hard to work around both.

One can use zsh's `=(...)` form of command substitution (`vd -f json =(cmd)`)  but that's not ideal as `cmd` and `vd` no  longer run concurrently and the whole  output needs to be stored on the filesystem.

**Comment by stephane-chazelas** [comment]
It seems this issue is a follow-up on #1018 which was not fully resolved.

**Comment by saulpw** [comment]
Thanks for the detailed report, @stephane-chazelas.  This should be fixed on develop branch now.
