### ISSUE TITLE
[question] is there a way to execute an sql query with native clickhouse functions?

### ISSUE THREAD

**Issue by maxim-uvarov** [saulpw/visidata#2058]
Guys, is there a way to execute sql with native clickhouse functions?
like:
```
SELECT signer, sum(fee) as fee FROM (
 SELECT
  signer,
toUInt128(JSONExtractString(arrayJoin(JSONExtractArrayRaw(JSONExtractString(fee,
  'coins'))),
  'amount')) as fee
 FROM
  spacebox.`transaction` FINAL
) _t
GROUP BY signer
ORDER BY fee DESC
```

I tried `exec-sql`, but VDSQL has quit with an error.

```
Traceback (most recent call last):
  File "/Users/user/miniconda3/envs/p311/bin/vdsql", line 7, in <module>
    rc = main()
         ^^^^^^
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/apps/vdsql/__main__.py", line 23, in main
    main.vd_cli()
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/main.py", line 364, in vd_cli
    rc = main_vd()
         ^^^^^^^^^
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/main.py", line 325, in main_vd
    run(vd.sheets[0])
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/vdobj.py", line 33, in _vdfunc
    return getattr(visidata.vd, func.__name__)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/extensible.py", line 57, in wrappedfunc
    return oldfunc(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/extensible.py", line 57, in wrappedfunc
    return oldfunc(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/mainloop.py", line 288, in run
    ret = vd.mainloop(scr)
          ^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/mainloop.py", line 220, in mainloop
    sheet.execCommand(self.keystrokes, keystrokes=self.keystrokes)
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/extensible.py", line 71, in wrappedfunc
    r = oldfunc(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/basesheet.py", line 203, in execCommand
    err = vd.exceptionCaught(e)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/basesheet.py", line 200, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/basesheet.py", line 73, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "search-keys", line 1, in <module>
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/search.py", line 81, in moveInputRegex
    r = vd.inputMultiple(regex=dict(prompt=f"{action} regex: ", type=type, defaultLast=True),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/_input.py", line 395, in inputMultiple
    input_kwargs['value'] = vd.input(**input_kwargs, attr=colors.color_edit_cell, bindings={
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/_input.py", line 447, in input
    ret = self.editText(y, promptlen, w=w,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/_input.py", line 319, in editText
    v = vd.editline(vd.activeSheet._scr, y, x, w, display=display, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/_input.py", line 258, in editline
    ch = vd.getkeystroke(scr)
         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/vdobj.py", line 132, in getkeystroke
    self.drainPendingKeys(scr)
  File "/Users/user/miniconda3/envs/p311/lib/python3.11/site-packages/visidata/vdobj.py", line 115, in drainPendingKeys
    scr.timeout(0)
    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'timeout'
 ```

**Comment by maxim-uvarov** [comment]
I should mention that my example from the initial post was created using a development version of vD that was 2 months old.

It seems like in the latest development version of VD Clickhouse support is broken

What I did:
```
git pull
conda create --name vd20231017 python=3.11
conda activate vd20231017
pip3 install .
pip install 'ibis-framework[clickhouse]'

cd apps/vdsql
pip install .
```

What I got:
I connected to a clickhouse db, I got an inital list of tables, I tryied to enter some tables but I got an error:

```
Traceback (most recent call last):
  File "/Users/user/miniconda3/envs/vd20231017/lib/python3.11/site-packages/visidata/threads.py", line 211, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/vd20231017/lib/python3.11/site-packages/visidata/sheets.py", line 233, in reload
    self.loader()
  File "/Users/user/miniconda3/envs/vd20231017/lib/python3.11/site-packages/visidata/sheets.py", line 253, in loader
    for r in self.iterload():
  File "/Users/user/miniconda3/envs/vd20231017/lib/python3.11/site-packages/visidata/apps/vdsql/clickhouse.py", line 25, in iterload
    self.preload()
    ^^^^^^^^^^^^
AttributeError: 'ClickhouseSheet' object has no attribute 'preload'
```

**Comment by maxim-uvarov** [comment]
Well, I bet it has nothing to do with built-in ClickHouse functions. It seems like ClickHouse integration in VDSQL is broken now. Or maybe I installed VDSQL improperly.

**Comment by saulpw** [comment]
Hey @maxim-uvarov, thanks for filing this issue.  The vdsql version on develop should work with clickhouse now, since b4f06453f58f4f6a90e8bf6b47fd88238f54355f.

Let us know if you are still having issues!

**Comment by maxim-uvarov** [comment]
Thank you, @saulpw!

Now I can open tables. 

But I can't execute the sql of a kind:
```
SELECT signer, sum(fee) as fee FROM (  SELECT   signer, toUInt128(JSONExtractString(arrayJoin(JSONExtractArrayRaw(JSONExtractString(fee,   'coins'))),   'amount')) as fee  FROM   spacebox.`transaction` FINAL ) _t GROUP BY signer ORDER BY fee DESC
```

I'm getting the error below. 
Is anything can be fixed quickly? Or is it far deep in clickhouse drivers? 

```
Traceback (most recent call last):
  File "/Users/user/miniconda3/envs/vd20231102/lib/python3.11/site-packages/visidata/basesheet.py", line 208, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/vd20231102/lib/python3.11/site-packages/visidata/basesheet.py", line 73, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "exec-sql", line 1, in <module>
    'VisiData: a curses interface for exploring and arranging tabular data'
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/vd20231102/lib/python3.11/site-packages/visidata/apps/vdsql/_ibis.py", line 118, in rawSql
    query=con.sql(qstr))
          ^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/vd20231102/lib/python3.11/site-packages/ibis/backends/clickhouse/__init__.py", line 76, in sql
    schema = self._get_schema_using_query(query)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/vd20231102/lib/python3.11/site-packages/ibis/backends/clickhouse/__init__.py", line 531, in _get_schema_using_query
    {
  File "/Users/user/miniconda3/envs/vd20231102/lib/python3.11/site-packages/ibis/backends/clickhouse/__init__.py", line 532, in <dictcomp>
    field["Name"]: ClickhouseType.from_string(field["Type"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/vd20231102/lib/python3.11/site-packages/ibis/backends/base/sqlglot/datatypes.py", line 178, in from_string
    return cls.to_ibis(sgtype, nullable=nullable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/vd20231102/lib/python3.11/site-packages/ibis/backends/base/sqlglot/datatypes.py", line 156, in to_ibis
    dtype = _from_sqlglot_types[typecode](nullable=cls.default_nullable)
            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: <Type.UINT128: 'UINT128'>
```

**Comment by maxim-uvarov** [comment]
And just for your information, if this is important: When I execute SQL with line breaks (probably because of the new command palette, which is super-super cool! I love it so much!), `vdsql` executes different commands, changes settings, and creates rows.

here is demo:
https://youtu.be/rwnO9JYPBaI
