### ISSUE TITLE
Exception when pressing `b`

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#2064]
Ubuntu. I just opened a folder and pressed `b`.

```
Traceback (most recent call last):
  File "/home/ramrachum/.local/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/home/ramrachum/.local/lib/python3.10/site-packages/visidata/main.py", line 379, in vd_cli
    rc = main_vd()
  File "/home/ramrachum/.local/lib/python3.10/site-packages/visidata/main.py", line 340, in main_vd
    run(vd.sheets[0])
  File "/home/ramrachum/.local/lib/python3.10/site-packages/visidata/vdobj.py", line 33, in _vdfunc
    return getattr(visidata.vd, func.__name__)(*args, **kwargs)
  File "/home/ramrachum/.local/lib/python3.10/site-packages/visidata/extensible.py", line 57, in wrappedfunc
    return oldfunc(*args, **kwargs)
  File "/home/ramrachum/.local/lib/python3.10/site-packages/visidata/extensible.py", line 57, in wrappedfunc
    return oldfunc(*args, **kwargs)
  File "/home/ramrachum/.local/lib/python3.10/site-packages/visidata/mainloop.py", line 299, in run
    ret = vd.mainloop(scr)
  File "/home/ramrachum/.local/lib/python3.10/site-packages/visidata/mainloop.py", line 181, in mainloop
    self.draw_all()
  File "/home/ramrachum/.local/lib/python3.10/site-packages/visidata/mainloop.py", line 115, in draw_all
    vd.drawSheet(vd.win1, ss1[0])
  File "/home/ramrachum/.local/lib/python3.10/site-packages/visidata/mainloop.py", line 45, in drawSheet
    self.drawSidebar(scr, sheet)
  File "/home/ramrachum/.local/lib/python3.10/site-packages/visidata/sidebar.py", line 42, in drawSidebar
    return sheet.drawSidebarText(scr, text=sidebar, overflowmsg=overflowmsg, bottommsg=bottommsg)
  File "/home/ramrachum/.local/lib/python3.10/site-packages/visidata/sidebar.py", line 50, in drawSidebarText
    text = textwrap.dedent(text.strip('\n'))
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by saulpw** [comment]
Thanks @cool-RR, this one should be fixed now.
