### ISSUE TITLE
[zip-http/json] Loading json from url_zip file fails with type error.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2127]
**Small description**
Loading json from zip file fails

**Expected result**
Loads json

**Actual result with screenshot**

https://asciinema.org/a/E9YcxJwaqQhXwKOfQdCvpeD17

```
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/visidata/threads.py", line 219, in _toplevelTryFunc
t.status = func(*args, **kwargs)
File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 251, in reload
self.loader()
File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 276, in loader
for r in self.iterload():
File "/usr/lib/python3.9/site-packages/visidata/loaders/json.py", line 38, in iterload
for L in fp:
File "/usr/lib/python3.9/site-packages/visidata/text_source.py", line 27, in __next__
line = self.readline()
File "/usr/lib/python3.9/site-packages/visidata/text_source.py", line 15, in readline
line = self._fp.readline()
File "/usr/lib/python3.9/site-packages/visidata/path.py", line 437, in readline
return next(self.iter)
File "/usr/lib/python3.9/site-packages/visidata/path.py", line 464, in __next__
r = next(self.rf.iter_lines)
File "/usr/lib/python3.9/codecs.py", line 1054, in iterdecode
output = decoder.decode(input)
File "/usr/lib/python3.9/codecs.py", line 321, in decode
data = self.buffer + input
TypeError: can't concat str to bytes
```

**Steps to reproduce with sample data and a .vd**

` vd https://osv-vulnerabilities.storage.googleapis.com/PyPI/all.zip`

Try to dive into a json file.

**Additional context**
Please include the version of VisiData and Python. latest develop Python 3.9.2

**Comment by anjakefala** [comment]
This bug is specifically for loading from the a url. If you download the file locally, and load it from there, all the data extracts + loads fine.

**Comment by anjakefala** [comment]
There used to be a `RecursionError` until this change: ceec18e289516c6a32090d928984fcd8ae4a5991. After which the `can't concat str to bytes` started.

The `RecursionError` started here :grimacing: a1affe7d8b60c4e9bdbca2c43c30416e42875d7f

**Comment by anjakefala** [comment]
This should now be fixed! Thanks @frosencrantz =)

**Comment by frosencrantz** [comment]
That is great.  Thanks @anjakefala for all the updates to get this working again.
