### ISSUE TITLE
[html] 'ValueError: Invalid IPv6 URL' when loading table with malformed URL

### ISSUE THREAD

**Issue by correctmost** [saulpw/visidata#2227]
**Small description**
VisiData fails to load an HTML sheet when there is a malformed URL present

**Expected result**
VisiData loads the sheet and ignores (or discards) the invalid URL

**Actual result with screenshot**
Backtrace:
```
Traceback (most recent call last):
  File "/home/s/.venv-visidata/lib/python3.11/site-packages/visidata/threads.py", line 219, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/s/.venv-visidata/lib/python3.11/site-packages/visidata/sheets.py", line 251, in reload
    self.loader()
  File "/home/s/.venv-visidata/lib/python3.11/site-packages/visidata/sheets.py", line 276, in loader
    for r in self.iterload():
  File "/home/s/.venv-visidata/lib/python3.11/site-packages/visidata/loaders/html.py", line 80, in iterload
    root.make_links_absolute(self.source.docinfo.URL)
  File "/home/s/.venv-visidata/lib/python3.11/site-packages/lxml/html/__init__.py", line 481, in make_links_absolute
    self.rewrite_links(link_repl)
  File "/home/s/.venv-visidata/lib/python3.11/site-packages/lxml/html/__init__.py", line 621, in rewrite_links
    new_link = link_repl_func(link.strip())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s/.venv-visidata/lib/python3.11/site-packages/lxml/html/__init__.py", line 476, in link_repl
    return urljoin(base_url, href)
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/parse.py", line 551, in urljoin
    urlparse(url, bscheme, allow_fragments)
  File "/usr/lib/python3.11/urllib/parse.py", line 395, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/parse.py", line 497, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

**Steps to reproduce with sample data and a .vd**

1 - Save the following HTML as `table.html`
```html
<table>
 <tr><td><a href="https://google.com]">1</a></td></tr>
</table>
```

2 - Run `vd table.html -N`
3 - Load `table_0` to trigger the ValueError

**Additional context**
There is an lxml bug report that mentions the addition of a `handle_failures` parameter to `make_links_absolute`: https://bugs.launchpad.net/lxml/+bug/1250557

API docs: https://lxml.de/api/lxml.html.HtmlMixin-class.html#make_links_absolute

VisiData v3.0
Python 3.11.6
lxml 5.0.0

**Comment by saulpw** [comment]
Thanks for the report, @correctmost!  I used `handle_failures="ignore"` and wrapped the urljoin so that in an error case it logs the error and just passes the href through.

**Comment by correctmost** [comment]
Thanks for fixing the bug!

Do these `urljoin` calls need similar changes?

https://github.com/saulpw/visidata/blob/6855213a19614dc254b59ac435c99e9c9f5a239c/visidata/loaders/html.py#L91-L98

https://github.com/saulpw/visidata/blob/6855213a19614dc254b59ac435c99e9c9f5a239c/visidata/loaders/scrape.py#L113-L115

**Comment by saulpw** [comment]
@correctmost I unfortunately don't have the bandwidth to audit dead code.  If you find a problematic case, please file an issue and we'll address it.
