### ISSUE TITLE
[dive-selected] Dive-selected traces on FreqTableSheet 

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2239]
**Small description**
Dive-selected `gEnter` traces on FreqTableSheet

**Expected result**
No traceback

**Actual result with screenshot**

 https://asciinema.org/a/64ZTseLE2OqoMOB1HWkJx1uac

```
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/visidata/sidebar.py", line 60, in drawSidebar
sidebar = sheet.formatString(sheet.guide, help=sheet.formatter_helpstr)
File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 293, in formatString
return MissingAttrFormatter().format(fmt, sheet=self, vd=vd, **kwargs)
File "/usr/lib/python3.9/string.py", line 161, in format
return self.vformat(format_string, args, kwargs)
File "/usr/lib/python3.9/string.py", line 165, in vformat
result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
File "/usr/lib/python3.9/string.py", line 205, in _vformat
obj, arg_used = self.get_field(field_name, args, kwargs)
File "usr/lib/python3.9/site-packages/visidata/utils.py", line 191, in get_field
return super().get_field(field_name, args, kwargs)
File "/usr/lib/python3.9/string.py", line 276, in get_field
obj = getattr(obj, i)
File "usr/lib/python3.9/site-packages/visidata/basesheet.py", line 181, in displaySource
return f'the *{self.source[0]}* sheet'
TypeError: 'FreqTableSheet' object is not subscriptable
```

**Steps to reproduce with sample data and a .vd**
First try reproducing without any user configuration by using the flag `-N`.
e.g. `echo "abc" | vd -f txt -N`

This does not happen for csv data, but via DirSheet:

`vd sample_data`

```
#!vd -p
{"sheet": null, "col": null, "row": null, "longname": "open-file", "input": "sample_data", "keystrokes": "o", "comment": null}
{"sheet": "sample_data", "col": "ext", "row": "", "longname": "freq-col", "input": "", "keystrokes": "Shift+F", "comment": "open Frequency Table grouped on current column, with aggregations of other columns"}
{"sheet": "sample_data_ext_freq", "col": "", "row": "\u30adxlsx", "longname": "select-row", "input": "", "keystrokes": "s", "comment": "select current row"}
{"sheet": "sample_data_ext_freq", "col": "", "row": "\u30adtsv", "longname": "select-row", "input": "", "keystrokes": "s", "comment": "select current row"}
{"sheet": "sample_data_ext_freq", "col": "", "row": "", "longname": "dive-selected", "input": "", "keystrokes": "gEnter", "comment": "open copy of source sheet with rows that are grouped in selected rows"}
```

Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**
Please include the version of VisiData and Python.  Latest develop branch Python 3.9.2

**Comment by anjakefala** [comment]
I guess we never tested that case! Thanks for the precise example. =)
