### ISSUE TITLE
vdsql 'ibis' NameError

### ISSUE THREAD

**Issue by fleimgruber** [saulpw/visidata#2248]
**Small description**
vdsql can't resolve `ibis`.

**Expected result**
vdsql is able to open a .ddb file.

**Actual result with screenshot**
```
saul.pw/VisiData v3.0.1
opening C:\Users\LeimgruberF\tmp\data.ddb as vdsql
Traceback (most recent call last):
  File "C:\Users\LeimgruberF\.pyenv\pyenv-win\versions\3.10.11\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\LeimgruberF\.pyenv\pyenv-win\versions\3.10.11\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\LeimgruberF\lg\.venv\Scripts\visidata.exe\__main__.py", line 7, in <module>
  File "C:\Users\LeimgruberF\lg\.venv\lib\site-packages\visidata\main.py", line 377, in vd_cli
    rc = main_vd()
  File "C:\Users\LeimgruberF\lg\.venv\lib\site-packages\visidata\main.py", line 299, in main_vd
    vs = vd.openSource(p, create=True, **opts) or vd.fail(f'could not open {p}')
  File "C:\Users\LeimgruberF\lg\.venv\lib\site-packages\visidata\_open.py", line 159, in openSource
    vs = vd.openPath(Path(p), filetype=filetype, create=create)  # convert to Path and recurse
  File "C:\Users\LeimgruberF\lg\.venv\lib\site-packages\visidata\_open.py", line 139, in openPath
    return openfunc(p)
  File "C:\Users\LeimgruberF\lg\.venv\lib\site-packages\visidata\apps\vdsql\_ibis.py", line 68, in open_vdsql
    setattr(ibis, p.ext, ext_aliases.get(p.ext))
NameError: name 'ibis' is not defined
```

**Steps to reproduce with sample data and a .vd**
Followed instructions from: https://github.com/saulpw/visidata/tree/develop/visidata/apps/vdsql#install-latest-release

Used Poetry instead of plain pip (poetry itself uses pip):

`pyproject.toml`:
```
[tool.poetry.dependencies]
...
vdsql = { path = "../dev/visidata/visidata/apps/vdsql", develop = false }
```

`visidata -f vdsql C:\Users\LeimgruberF\tmp\data.ddb`

**Additional context**
Python 3.10.11
VisiData 3.0.1

**Comment by anjakefala** [comment]
@fleimgruber This should be fixed on `develop`!

**Comment by fleimgruber** [comment]
@anjakefala thanks for letting me know! I am seeing this now with "duckdb" extra installed with ibis-framework, let me know if I should open another issue for that:

![image](https://github.com/saulpw/visidata/assets/7400038/426259bd-679e-4412-a811-1bf3e56960dc)

**Comment by anjakefala** [comment]
Yes, please open a seperate issue!

**Comment by fleimgruber** [comment]
Separate issue: #2259
