### ISSUE TITLE
Pypy Crashes

### ISSUE THREAD

**Issue by gordo-veda** [saulpw/visidata#2284]
Pypy 3.10-7.3.15 leads to a crash.

To reproduce:

`brew install pypy3.10`
`mkvirtualenv visidata-pypy -p /usr/local/Cellar/pypy3.10/7.3.15/bin/pypy3`
`pip install visidata`
`touch blank.txt`
`vd blank.txt`

You can also reproduce with `pypy` from `pyenv`.

```
Traceback (most recent call last):
File "~/.virtualenvs/visidata-pypy/bin/vd", line 6, in <module>
visidata.main.vd_cli()
File "~/.virtualenvs/visidata-pypy/lib/pypy3.10/site-packages/visidata/main.py", line 381, in vd_cli
rc = main_vd()
^^^^^^^^^
File "~/.virtualenvs/visidata-pypy/lib/pypy3.10/site-packages/visidata/main.py", line 341, in main_vd
run(vd.sheets[0])
File "~/.virtualenvs/visidata-pypy/lib/pypy3.10/site-packages/visidata/vdobj.py", line 33, in _vdfunc
return getattr(visidata.vd, func.__name__)(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.virtualenvs/visidata-pypy/lib/pypy3.10/site-packages/visidata/extensible.py", line 65, in wrappedfunc
return oldfunc(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.virtualenvs/visidata-pypy/lib/pypy3.10/site-packages/visidata/extensible.py", line 65, in wrappedfunc
return oldfunc(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.virtualenvs/visidata-pypy/lib/pypy3.10/site-packages/visidata/extensible.py", line 65, in wrappedfunc
return oldfunc(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.virtualenvs/visidata-pypy/lib/pypy3.10/site-packages/visidata/mainloop.py", line 313, in run
scr = vd.initCurses()
^^^^^^^^^^^^^^^
File "~/.virtualenvs/visidata-pypy/lib/pypy3.10/site-packages/visidata/extensible.py", line 79, in wrappedfunc
r = oldfunc(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.virtualenvs/visidata-pypy/lib/pypy3.10/site-packages/visidata/mainloop.py", line 286, in initCurses
vd.drainPendingKeys(scr)
File "~/.virtualenvs/visidata-pypy/lib/pypy3.10/site-packages/visidata/vdobj.py", line 127, in drainPendingKeys
k = self.get_wch(scr)
^^^^^^^^^^^^^^^^^
File "~/.virtualenvs/visidata-pypy/lib/pypy3.10/site-packages/visidata/vdobj.py", line 115, in get_wch
return scr.get_wch()
^^^^^^^^^^^^^
File "/usr/local/Cellar/pypy3.10/7.3.15/libexec/lib/pypy3.10/_curses.py", line 461, in get_wch
wch = ffi.new("wint_t[1]")
^^^^^^^^^^^^^^^^^^^^
ffi.error: undefined type name
wint_t[1]
^
```

**Comment by saulpw** [comment]
Looks like a problem with upstream curses.  We don't have plans to actively support pypy anyway.
