### ISSUE TITLE
Log file inside zip file erroneously guessed as "tar" instead of text

### ISSUE THREAD

**Issue by krackout** [saulpw/visidata#2316]
Log file inside zip file erroneously guessed as "tar" instead of text. Visidata version 3.0.2.

On 2.11 it's correctly opened as text.

**Comment by anjakefala** [comment]
Hi @krackout!

Thanks for filing this issue. Please provide some sample data, so that we can reproduce this. We might not be able to fix it otherwise.

**Comment by krackout** [comment]
Inside somelogs.zip file, there's a freshclam.log which produces the error.
[somelogs.zip](https://github.com/saulpw/visidata/files/14301136/somelogs.zip)

I also attach a screenshot of the error.
![visidata-logfile-error](https://github.com/saulpw/visidata/assets/36501063/d85147d8-8ff2-481f-8ca3-264740beac17)

**Comment by ajkerrigan** [comment]
Seeing the same thing here, repro:

```console
echo "hiya" > test.log
zip test.zip test.log
vd -N test.zip
```

Then hitting `Enter` gives me the same thing @krackout showed. Full traceback:

```console
Traceback (most recent call last):
File "/home/aj/.local/pipx/venvs/visidata/lib/python3.12/site-packages/visidata/threads.py", line 220, in _toplevelTryFunc
t.status = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/home/aj/.local/pipx/venvs/visidata/lib/python3.12/site-packages/visidata/sheets.py", line 260, in reload
self.loader()
File "/home/aj/.local/pipx/venvs/visidata/lib/python3.12/site-packages/visidata/sheets.py", line 285, in loader
for r in self.iterload():
File "/home/aj/.local/pipx/venvs/visidata/lib/python3.12/site-packages/visidata/loaders/archive.py", line 140, in iterload
with tarfile.open(name=str(self.source)) as tf:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/tarfile.py", line 1808, in open
raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: ReadError('not an lzma file')
- method tar: ReadError('truncated header')
```

Bisect tells me that this started in https://github.com/saulpw/visidata/commit/eb9d9c434e6b0c60a8b7035a9c98c62c18642206.

If I use `p.open_bytes()` instead of `p.fp` [here](https://github.com/saulpw/visidata/commit/eb9d9c434e6b0c60a8b7035a9c98c62c18642206#diff-24a0b71ea1df3b5473491377e4dc7c5632a0aafe4cf52a59ef99d43aa4f038e4R18) locally it seems to do good things, in that:

- A `.log` inside a `.zip` will still open as txt
- Tar files still open properly, and renaming `test.tar` to `test.taradjacent` gets properly guessed/opened as `tar`

Guessing doesn't work for a tar file named `test.taradjacent` _inside a zip file_... but I can't tell if we expect that level of nested guessing to work :thinking:

**Comment by anjakefala** [comment]
Thanks for investigating! =)

Wrt that commit, for any fixes, we'll also have to check up on this behaviour: https://github.com/saulpw/visidata/pull/1978

**Comment by ajkerrigan** [comment]
> Thanks for investigating! =)
> 
> Wrt that commit, for any fixes, we'll also have to check up on this behaviour: #1978

Good call, thanks! Ok repro matrix time :sweat_smile: . There are a few candidates for [that line](https://github.com/saulpw/visidata/commit/eb9d9c434e6b0c60a8b7035a9c98c62c18642206#diff-24a0b71ea1df3b5473491377e4dc7c5632a0aafe4cf52a59ef99d43aa4f038e4R18):

```python
   if tarfile.is_tarfile(p):
   if tarfile.is_tarfile(p.fp):
   if tarfile.is_tarfile(p.open_bytes()):
```

And a few cases to check:

1. Do we drop rows reading from stdin, in a test case [like this](https://github.com/midichef/visidata/blob/022f4b001eea4315210170fa77d76fe21cc549dd/dev/test.sh#L45)?
2. If we rename a tar file to an unknown extension, does it open as a tar?
  2a. What if it's in a zip file?
  2b. Or if we open it via stdin?
3. if we open a non-tar file with an unknown extension, does it open as txt?
  3a. What if it's in a zip file?
  3b. Or if we open it via stdin? (e.g. `vd -N <(cat <file>)` or `cat <file> | vd -N`) 

And from some testing the results look like...

-----

```python
   if tarfile.is_tarfile(p):
```

1. :x: Drops rows when reading from stdin, disqualified :sweat_smile: 

-----

```python
   if tarfile.is_tarfile(p.fp):
```

1. :heavy_check_mark:
2. :x: `guess_tar: nothing to open`
  2a. :heavy_check_mark:
  2b. :x: `guess_tar: illegal seek`
3. :heavy_check_mark: 
  3a. :x: Incorrectly guesses as tar and then throws `ReadError`s (the core of this GH issue)
  3b. :heavy_check_mark: 

-----

```python
   if tarfile.is_tarfile(p.open_bytes()):
```

1. :heavy_check_mark: 
2. :heavy_check_mark: 
  2a. :x: `guess_tar: a RepeatFile holds text and cannot be reopened in binary mode`, opens as `txt`
  2b. :x: `guess_tar: a RepeatFile holds text and cannot be reopened in binary mode`, opens as `txt`
3. :heavy_check_mark: 
  3a. :heavy_check_mark: 
  3b. :heavy_check_mark: 

-----

So I _think_ none of the options I listed are perfect, but `p.open_bytes()` seems to fail the least :sweat_smile: . Its main drawback is that it can't properly identify a `tar` file with a non-tar extension, being opened from stdin or inside an archive. Maybe that's an issue that's worth digging into separately, or it's a rare enough combination of edge cases that we consciously punt on it? :thinking:

**Comment by saulpw** [comment]
> So I think none of the options I listed are perfect, but p.open_bytes() seems to fail the least 😅 . Its main drawback is that it can't properly identify a tar file with a non-tar extension, being opened from stdin or inside an archive. Maybe that's an issue that's worth digging into separately, or it's a rare enough combination of edge cases that we consciously punt on it? 🤔

I think it should be rare enough that we can punt on it for now.  Ultimately we should head towards filetype being composable, e.g. `zip+tar+txt` so that you can specify the filetype for each layer of container independently.  Until then, sorry about your log file inside a tarball inside a zip file.

**Comment by krackout** [comment]
It must be an edge case indeed; I supposed it would be easy to fix, since it worked on v2.11.

**Comment by anjakefala** [comment]
> It must be an edge case indeed; I supposed it would be easy to fix, since it worked on v2.11.

v2.11 did not have the filetype guesser logic! That's why the behaviour changed. =)

**Comment by midichef** [comment]
I've been sitting on a mostly-finished patch that addresses the issue of `is_tarfile()` needing a binary file. It also would allow Visidata to guess binary filetypes, like `guess_zip()`, when reading data piped to stdin.

Currently, visidata saves stdin data into a `RepeatFile`, which reads the data as text, and saves it to be read multiple times for "files" opened in text mode. The change is to make a `RepeatBinaryFile` that saves the incoming data as binary bytes instead. Then it can be reread directly as bytes for binary "files", or encoded and served as text for text "files".

If there's interest, I can put up what I've got as a starting point. But it needs to be finished, and then tested thoroughly. I can't do that in the near future.

**Comment by saulpw** [comment]
I would love to see that, @midichef.  I don't have time myself right now either, but maybe it will inspire another enterprising VisiDatan to kick the tires on it.

**Comment by ajkerrigan** [comment]
I'm curious too. I would definitely need some time to spin up on the changes and ripple effects. Happy to kick the tires and work through issues though. I'm onboard with the motivation for sure, so it's very cool that you've already got something started! ❤️

**Comment by krackout** [comment]
>Until then, sorry about your log file inside a tarball inside a zip file.

@saulpw Apparently you misunderstood. It's a text file with .log extension, inside a zip file. The text/log file is guessed erroneously as tar, no tar involved.

**Comment by saulpw** [comment]
@krackout I was being a little cheeky, the 'you' here was referring to the hypothetical user for a tar file within an archive:

>  Its main drawback is that it can't properly identify a tar file with a non-tar extension, being opened from stdin or inside an archive.

**Comment by midichef** [comment]
An update to my comment a couple of months ago:
> I've been sitting on a mostly-finished patch

I've been prioritizing fixing Visidata bugs, but now I can resume work on this feature. I will likely have a workable version ready within a week.

**Comment by midichef** [comment]
Update on this patch:  it's been a few months. I got hung up with a bug that I didn't understand. I feel the patch is too experimental to be part of visidata 3.1. I'll submit it after visidata 3.1 is released so it gets more time to be tested.

**Comment by anjakefala** [comment]
@midichef We welcome opening the PR if you still have it. You're right, we won't rush it for the upcoming release.

**Comment by midichef** [comment]
@anjakefala I'll resume work on the patch this month. It'll take quite a bit of time, as it's only a rough prototype, and it'll need extensive testing.

**Comment by saulbert** [comment]
This was fixed in c98ccfd8 by using `p.open_bytes()` instead of `p.fp` in `guess_tar()`. Non-tar files inside zip archives are no longer misidentified as tar.

A regression test has been added in c5c2a650.

[this message written by Claude Opus 4.6 and approved by @saulpw]

**Comment by saulpw** [comment]
What @saulbert said seems to be true for the top-line bug. Any other issues that arose in this thread that are still around, let's create a new issue for.
