### ISSUE TITLE
addcol-new fails in batch mode

### ISSUE THREAD

**Issue by cwarden** [saulpw/visidata#251]
`addcol-new` fails in batch mode:

```
$ vd --debug -b -p newCol.vd
Think about what you're doing
opening newCol as vd
"."
opening . as dir
"1"
c=addColumn(SettableColumn("", width=options.default_width), cursorColIndex+1); draw(vd.scr); cursorVisibleColIndex=visibleCols.index(c); c.name=editCell(cursorVisibleColIndex, -1); c.width=None
AttributeError: 'NoneType' object has no attribute 'erase'
AttributeError: 'NoneType' object has no attribute 'erase'
Traceback (most recent call last):
  File "/usr/local/bin/vd", line 4, in <module>
    __import__('pkg_resources').run_script('visidata==1.6.dev0', 'vd')
  File "/home/cwarden/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/cwarden/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1451, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/visidata-1.6.dev0-py3.6.egg/EGG-INFO/scripts/vd", line 169, in <module>
  File "/usr/local/lib/python3.6/dist-packages/visidata-1.6.dev0-py3.6.egg/EGG-INFO/scripts/vd", line 152, in main
  File "/usr/local/lib/python3.6/dist-packages/visidata-1.6.dev0-py3.6.egg/visidata/cmdlog.py", line 289, in replay_sync
  File "/usr/local/lib/python3.6/dist-packages/visidata-1.6.dev0-py3.6.egg/visidata/vdtui/__init__.py", line 455, in exceptionCaught
  File "/usr/local/lib/python3.6/dist-packages/visidata-1.6.dev0-py3.6.egg/visidata/cmdlog.py", line 284, in replay_sync
  File "/usr/local/lib/python3.6/dist-packages/visidata-1.6.dev0-py3.6.egg/visidata/cmdlog.py", line 264, in replayOne
  File "/usr/local/lib/python3.6/dist-packages/visidata-1.6.dev0-py3.6.egg/visidata/vdtui/__init__.py", line 1132, in exec_command
  File "/usr/local/lib/python3.6/dist-packages/visidata-1.6.dev0-py3.6.egg/visidata/vdtui/__init__.py", line 1126, in exec_command
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/visidata-1.6.dev0-py3.6.egg/visidata/vdtui/_sheet.py", line 566, in draw
AttributeError: 'NoneType' object has no attribute 'erase'
```

Here's the [cmdlog](https://gist.github.com/ada3b87d1eac75efd11ac28f73920af8).

**Comment by anjakefala** [comment]
Hi @cwarden!

Nice catch! =D

Previously, `addcol-new` used to query for the new column name on the status line. Since 1.5, it instead creates the new column immediately and starts the user off in *edit mode* on the column header. 

The issue originated with this change. This can be fixed, and is not a problem, but it would be great to know yours' (and other folks') preference with respect to `addcol-new` behaviour. How do you feel about creating the column and starting off in the header? 

Essentially, if it is not desired behaviour, we should probably not further complicate it by working around this bug and instead just revert to previous behaviour. If it is desired, then we will polish it further up.

**Comment by cwarden** [comment]
The new behavior feels a little nicer in interactive mode, but it is inconsistent with `addcol-expr`, for example so no objection to reverting to the old behavior.  (I'm now thinking it would be neat to have `addcol-expr` work the same way and calculate the value of the new column for the visible rows as you type the expression.)

**Comment by saulpw** [comment]
Well, I hope the mess above fixed it :)
