### ISSUE TITLE
Can't use v3.1 - cannot import GuideSheet

### ISSUE THREAD

**Issue by wiraki** [saulpw/visidata#2561]
**Small description**

Updated to v3.1 and visidata won't start.

**Data to reproduce**

NA

**Steps to reproduce**

1. `pip install --upgrade visidata` (was successful)
2. Test with `vd --version` or try to open file with `vd`

**Actual result with screenshot**

```
Traceback (most recent call last):
  File "/home/marc/.local/bin/vd", line 3, in <module>
    import visidata.main
  File "/home/marc/.local/lib/python3.10/site-packages/visidata/__init__.py", line 157, in <module>
    importFeatures()
  File "/home/marc/.local/lib/python3.10/site-packages/visidata/__init__.py", line 139, in importFeatures
    vd.importSubmodules('visidata.features')
  File "/home/marc/.local/lib/python3.10/site-packages/visidata/settings.py", line 508, in importSubmodules
    vd.importModule(pkgname + '.' + module.name)
  File "/home/marc/.local/lib/python3.10/site-packages/visidata/settings.py", line 491, in importModule
    r = importlib.import_module(pkgname)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/marc/.local/lib/python3.10/site-packages/visidata/features/errors_guide.py", line 1, in <module>
    from visidata import GuideSheet, vd
ImportError: cannot import name 'GuideSheet' from partially initialized module 'visidata' (most likely due to a circular import) (/home/marc/.local/lib/python3.10/site-packages/visidata/__init__.py)
```

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)?

Yes.

- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)?

Yes.

**Additional context**

- What platform and version are you using (Linux, MacOS, Windows)?

Linux

- Which version of Python?

3.10.12

- Which terminal are you using (for display and input issues)?

NA

**Comment by anjakefala** [comment]
Hi @wiraki!

Thanks for letting us know. This should now be fixed with v3.1.1!

**Comment by m-pauper** [comment]
Thank **you** for the quick reaction!

**Comment by wiraki** [comment]
Thank **you** for the quick reaction!
