### ISSUE TITLE
undoing column additions causes `IndexError` in `allAggregators`

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#2607]
**Small description**
After adding a column, undoing the add causes an error.

**Steps to reproduce**
Open any visidata sheet, then `i` then `U`:
`vd sample_data/sample.tsv`

**Expected result**
The column insertion is undone, with normal status.

**Actual result with screenshot**
The column insertion is undone, but an error appears:
```
Traceback (most recent call last):
  File "/home/j/.venv/lib/python3.10/site-packages/visidata/mainloop.py", line 252, in mainloop
    vd.callNoExceptions(sheet.checkCursor)
...
  File "/home/midichef/.venv/lib/python3.10/site-packages/visidata/sheets.py", line 643, in checkCursor
    elif self.bottomRowIndex < self.cursorRowIndex:
...
  File "/home/midichef/.venv/lib/python3.10/site-packages/visidata/sheets.py", line 780, in allAggregators
    col = self.availCols[vcolidx]
IndexError: list index out of range
```

The error is probably related to caching. Clearing caches prevented [the same traceback after hiding a column](https://github.com/saulpw/visidata/pull/2578#issuecomment-2436796516).

**Configuration**
visidata v3.2dev
Python 3.10.12

**Comment by midichef** [comment]
Another way to trigger the same bug:
```
echo '{"A": [1, 2, 3]}' |vd -f json
```
then `expand-col` and `contract-col`

**Comment by saulpw** [comment]
Thanks for those repros, @midichef.  I made it so that both undo and contract_cols (two different codepaths for the two repros) call `calcColLayout()`, which now also calls `vd.clearCaches()`.
