### ISSUE TITLE
lxml is not bundled

### ISSUE THREAD

**Issue by nicwaller** [saulpw/visidata#320]
This [video](https://www.youtube.com/watch?v=0iJ9F4uTkz8) shows off Visidata's feature to import html tables from Wikipedia. When I tried it out myself, I got an error about lxml being unavailable.

### Steps to reproduce
```shell
vd https://en.wikipedia.org/wiki/List_of_candidates_by_riding_for_the_43rd_Canadian_federal_election
```
### Expected Result
Visidata scrapes the HTML and shows all the tables found.

### Actual Result
Visidata catches a ModuleNotFoundError and reports it in yellow text at the bottom of the screen.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/visidata/1.5.2/libexec/lib/python3.7/site-packages/visidata/vdtui.py", line 650, in toplevelTryFunc
    ret = func(*args, **kwargs)
  File "/usr/local/Cellar/visidata/1.5.2/libexec/lib/python3.7/site-packages/visidata/loaders/html.py", line 21, in reload
    import lxml.html
ModuleNotFoundError: No module named 'lxml'
```

### Workaround
I installed `lxml` in the Python virtualenv created by Homebrew.

```shell
/usr/local/Cellar/visidata/1.5.2/libexec/bin/pip3 install lxml
```

### Additional Details
```
nicwaller$ brew --version
Homebrew 2.1.7
Homebrew/homebrew-core (git revision f45e; last commit 2019-07-22)
```

macOS 10.14.5 (18F132)

**Comment by anjakefala** [comment]
I really loved this issue structure @nicwaller. ++

I agree with you that the lxml loader is a core one. I also missed it when installing VisiData through homebrew.

I am going to submit a patch to https://github.com/saulpw/homebrew-vd to include it and I am going to add your workaround to the docs.
