### ISSUE TITLE
yaml loader fails if the input is a dictionary

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#327]
I tried loading yaml that is just a dictionary, e.g.
foo: 1
bar: 2

The code expects only an array to be returned:

 Traceback (most recent call last):
   File "/usr/lib/python3.6/site-packages/visidata/threads.py", line 191, in _toplevelTryFunc 
     t.status = func(*args, **kwargs)
   File "/usr/lib/python3.6/site-packages/visidata/loaders/yaml.py", line 15, in reload
     for k in self.rows[0]:
 KeyError: 0

**Comment by anjakefala** [comment]
Pushed a fix! Let me know how it works out for you. Also, note that you can use `Ctrl+Y` to investigate dict row objects. =)
