### ISSUE TITLE
changing fmtstr causes error when replaying cmdlog

### ISSUE THREAD

**Issue by MarkoM2** [saulpw/visidata#332]
**Small description**
I created a cmdlog.vd to process some time series data and included changes of the fmtstr to display the date in another fashion. That worked. However when I changed the fmtstr of a data column to display more digits, vd throws an error when replaying the cmdlog.vd file. 

Changing the fmtstr while in the session works btw.

**Actual result with screenshot**
The error message is this:
```
> vd -p ~/.coinmon/calcpf2.vd
Traceback (most recent call last):
  File "/usr/bin/vd", line 152, in <module>
    main()
  File "/usr/bin/vd", line 139, in main
    vs = eval_vd(vdfile, *fmtargs, **fmtkwargs)
  File "/usr/bin/vd", line 16, in eval_vd
    log = logpath.read_text().format(*args, **kwargs)
IndexError: tuple index out of range
```

**Steps to reproduce with sample data and a .vd**
cmdlog.vd is this:
```
sheet	col	row	longname	input	keystrokes	comment
			open-file	/home/pi/.coinmon/portfoliolog_2.csv	o	
portfoliolog_2	date		type-date		@	
portfoliolog_2			columns-sheet		C	
portfoliolog_2_columns		キBTC rate in EUR	select-row		s	
portfoliolog_2_columns		キBTC balance	select-row		s	
portfoliolog_2_columns		キETH rate in EUR	select-row		s	
portfoliolog_2_columns		キETH balance	select-row		s	
portfoliolog_2_columns		キUSDC rate in EUR	select-row		s	
portfoliolog_2_columns		キUSDC balance	select-row		s	
portfoliolog_2_columns		キUSDC balance	type-float-selected		g%	
portfoliolog_2_columns			quit-sheet		q	
portfoliolog_2	BTC rate in EUR		rename-col	BTCrate	^	
portfoliolog_2	BTC balance		rename-col	BTCbalance	^	
portfoliolog_2	ETH rate in EUR		rename-col	ETHrate	^	
portfoliolog_2	ETH balance		rename-col	ETHbalance	^	
portfoliolog_2	USDC rate in EUR		rename-col	USDCrate	^	
portfoliolog_2	USDC balance		rename-col	USDCbalance	^	
portfoliolog_2	USDCbalance		addcol-expr	BTCrate*BTCbalance+ETHrate*ETHbalance+USDCrate*USDCbalance	=	
portfoliolog_2	BTCrate*BTCbalance+ETHrate*ETHbalance+USDCrate*USDCbalance		type-float		%	
portfoliolog_2	BTCrate*BTCbalance+ETHrate*ETHbalance+USDCrate*USDCbalance		rename-col	Portfolio	^	
portfoliolog_2	date		key-col		!	
portfoliolog_2			columns-sheet		C	
portfoliolog_2_columns	fmtstr	キdate	edit-cell	%Y-%m-%d %H:%M:%S	e	
portfoliolog_2_columns	fmtstr	キBTCbalance	edit-cell	{:.06f}	e	
portfoliolog_2_columns	fmtstr	キETHbalance	edit-cell	{:.06f}	e	
portfoliolog_2_columns			quit-sheet		q	
```
Sampledata would be:
```
date,BTC rate in EUR,BTC balance,ETH rate in EUR,ETH balance,USDC rate in EUR,USDC balance
2019-08-14 15:55:05,9480.22705033,0.05898837,184.733014075,0,0.8967292765,0
2019-08-14 16:00:04,9488.46350771,0.05898837,184.67089068,0,0.8967904687,0
2019-08-14 16:05:04,9486.9116839,0.05898837,184.892745657,0,0.8984322335,0
2019-08-14 16:10:05,9479.97697304,0.05898837,184.730015651,0,0.8984378446,0
2019-08-14 16:15:04,9473.84148799,0.05898837,184.078152967,0,0.9001130957,0
2019-08-14 16:20:05,9453.96604769,0.05898837,183.908557244,0,0.8991447542,0
2019-08-14 16:25:04,9440.25403943,0.05898837,183.929830584,0,0.8994170165,0
2019-08-14 16:30:04,9432.5424575,0.05898837,184.186597467,0,0.8986506015,0
2019-08-14 16:35:05,9448.58308622,0.05898837,184.497965697,0,0.8973933275,0
2019-08-14 16:40:04,9444.98969051,0.05898837,184.709042811,0,0.8979155624,0
2019-08-14 16:45:05,9435.3329251,0.05898837,184.53183512,0,0.9016262956,0
2019-08-14 16:50:05,9420.52973361,0.05898837,184.12941191,0,0.9010231825,0
```

**Additional context**
Version of VisiData: 
saul.pw/VisiData v1.5.2

**Comment by anjakefala** [comment]
Thanks for a great bug report @MarkoM2!

The good news is that it helped me figure out that this issue is actually already fixed on `develop`. =D
