### ISSUE TITLE
[develop] Integrate deferred changes into Canvas

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#334]
**Small description**
The deferred changes feature in 2.-1 resulted in adjustments to `delete-rows` within `clipboard.py`. Canvas commands, which delete the source rows within the current cursor, have not been updated.

**Expected result**
`delete-cursor` should mirror deletions on regular sheets. It should delete the source rows that are within the cursor. Those rows can be reloaded with `^R` until a save is performed on the source sheet. Those points should disappear from the plot.

**Actual result with screenshot**
~~~
Traceback (most recent call last):
  File "/home/kefala/git/visidata/visidata/basesheet.py", line 114, in exec_command
    exec(code, vdglobals, LazyMap(vd, self))
  File "delete-cursor", line 1, in <module>
    import math
AttributeError: 'CsvSheet' object has no attribute 'delete'
~~~

**Steps to reproduce with sample data and a .vd**
Run [tests/graphpr-nosave.vd](https://raw.githubusercontent.com/saulpw/visidata/develop/tests/graphpr-nosave.vd). Encapsulate some points with the cursor and press `d`.

**Additional context**
This is in testing 2.-1.
This issue does not occur in 1.5.2.

**Comment by anjakefala** [comment]
Modified tag to [develop] because this is an issue even when the `defermods` plugin is not installed.
