### ISSUE TITLE
If two source sheets loaded, upon startup prev-sheet will stacktrace

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#342]
**Running the prev-sheet command will stack trace if no other sheet visited**

**Expected result**
Swap to other sheet that was listed on the command line.  I listed two datasources on the command line, expected the prev-sheet to visit the other sheet (which would be more useful) or do nothing.  Didn't expect a stack trace.

**Actual result with screenshot**
Easy to reproduce.  I don't have the stack trace at time of report, available upon request

**Steps to reproduce with sample data and a .vd**
```
vd /path/to/data/dir   two.csv
Type '^^' prev-sheet  as first command
```

**Additional context**
Latest develop version

**Comment by anjakefala** [comment]
```
 I listed two datasources on the command line
```

Note, for reproducing this is key. If you loaded a single sheet and pressed `prev-sheet`, it would have just given the appropriate error.

**Comment by frosencrantz** [comment]
There is also a stack trace when quiting, and in several cells in the Sheets table.

**Comment by saulpw** [comment]
Nice find, thanks for the bug report. I'm thinking maybe vd.sheets should be readonly or private; everyone should use vd.push instead.

**Comment by frosencrantz** [comment]
With the latest changes, I still see a stack trace when quitting:

```
Traceback (most recent call last):
  File "/usr/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/usr/lib/python3.6/site-packages/visidata/main.py", line 199, in vd_cli                                                                                                                                                               
    rc = main()
  File "/usr/lib/python3.6/site-packages/visidata/main.py", line 172, in main
    run(vd.sheets[0])
  File "/usr/lib/python3.6/site-packages/visidata/mainloop.py", line 145, in run 
    ret = wrapper(cursesMain, sheetlist)
  File "/usr/lib/python3.6/site-packages/visidata/mainloop.py", line 137, in wrapper
    return curses.wrapper(setupcolors, f, *args)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3.6/site-packages/visidata/mainloop.py", line 134, in setupcolors
    return f(stdscr, *args)
  File "/usr/lib/python3.6/site-packages/visidata/mainloop.py", line 158, in cursesMain
    return vd.run(_scr)
  File "/usr/lib/python3.6/site-packages/visidata/mainloop.py", line 47, in run 
    self.draw(scr, sheet)
  File "/usr/lib/python3.6/site-packages/visidata/mainloop.py", line 24, in draw
    self.drawRightStatus(scr, sheets[0])  # visible during this getkeystroke
  File "/usr/lib/python3.6/site-packages/visidata/statusbar.py", line 132, in drawRightStatus
    vd.rightStatus(vs),
  File "/usr/lib/python3.6/site-packages/visidata/statusbar.py", line 120, in rightStatus
    status = '%9d %s' % (len(sheet), sheet.rowtype)
  File "/usr/lib/python3.6/site-packages/visidata/sheets.py", line 146, in __len__
    return self.nRows
  File "/usr/lib/python3.6/site-packages/visidata/sheets.py", line 341, in nRows
    return len(self.rows)
TypeError: object of type 'object' has no len()
```

**Comment by anjakefala** [comment]
I see the errors in the SheetsSheets cell. I believe those are because only the sheet at the top of the stack has been loaded upon startup. If you press Enter on the sheets with errors, their cells will not contain errors afterwards.

I cannot reproduce the quitting stacktrace; things work as expected for me. Are you quitting with `gq`? Can you walk through the steps you are taking?

**Comment by anjakefala** [comment]
Ah, got it!

If you quit with `q` before all of the sheets are loaded, that  stacktrace will be populated in stdout.

To reproduce

~~~
bin/vd sample_data/sample.tsv sample_data/benchmark.csv
~~~

Then press `Shift+S` to see that `benchmark` is not loaded and press `q` until you exit fully.
If you load `benchmark` before quitting, the errors in the cells disappear and the stacktrace does not appear.

(I think this still counts as a bug for us to fix.)

**Comment by saulpw** [comment]
Semantics for first load changed from vd.push to just before draw().
