### ISSUE TITLE
module tasklib has no attribute TaskWarrior

### ISSUE THREAD

**Issue by isomorphisms** [saulpw/visidata#386]
```
$ bin/vtask
Traceback (most recent call last):
  File "bin/vtask", line 104, in <module>
    run(TodoSheet('todos', source=Path('~/.task')))
  File "/usr/lib/python3.6/site-packages/visidata/vdtui.py", line 2841, in run
    ret = wrapper(cursesMain, sheetlist)
  File "/usr/lib/python3.6/site-packages/visidata/vdtui.py", line 2831, in wrapper
    return curses.wrapper(setupcolors, f, *args)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3.6/site-packages/visidata/vdtui.py", line 2828, in setupcolors
    return f(stdscr, *args)
  File "/usr/lib/python3.6/site-packages/visidata/vdtui.py", line 2851, in cursesMain
    vd().push(vs)  # first push does a reload
  File "/usr/lib/python3.6/site-packages/visidata/vdtui.py", line 961, in push
    vs.reload()
  File "bin/vtask", line 71, in reload
    self.tw = tasklib.TaskWarrior(data_location=self.source.resolve(), create=True)
AttributeError: module 'tasklib' has no attribute 'TaskWarrior'
```

**Comment by saulpw** [comment]
Hm, this one works for me.  what version of tasklib do you have installed?

**Comment by saulpw** [comment]
Assuming this is due to the wrong version being used.

Root solution: `vtask` will become a module, which depends on the exact version of TaskWarrior/tasklib it's been tested with.  That should help to avoid this problem in the future.
