### ISSUE TITLE
"No module named 'requests'" when loading wikipedia URL on NixOS

### ISSUE THREAD

**Issue by WesleyAC** [saulpw/visidata#437]
**Small description**

I ran `vd https://en.wikipedia.org/wiki/New_York_City_Subway_stations`, on NixOS (using the `visidata` nixOS package).

**Expected result**

visidata runs and opens the tables in the requested wikipedia page

**Actual result with screenshot**

```
Traceback (most recent call last):
  File "/nix/store/pf173kdl821b0g753yzfiibymyvxr0wz-visidata-1.5.2/bin/.vd-wrapped", line 153, in <module>
    main()
  File "/nix/store/pf173kdl821b0g753yzfiibymyvxr0wz-visidata-1.5.2/bin/.vd-wrapped", line 119, in main
    vs = openSource(src)
  File "/nix/store/pf173kdl821b0g753yzfiibymyvxr0wz-visidata-1.5.2/lib/python3.7/site-packages/visidata/data.py", line 239, in openSource
    return openSource(UrlPath(p), filetype)  # convert to Path and recurse
  File "/nix/store/pf173kdl821b0g753yzfiibymyvxr0wz-visidata-1.5.2/lib/python3.7/site-packages/visidata/data.py", line 246, in openSource
    return getGlobals()[openfunc](p, filetype=filetype)
  File "/nix/store/pf173kdl821b0g753yzfiibymyvxr0wz-visidata-1.5.2/lib/python3.7/site-packages/visidata/loaders/http.py", line 17, in openurl_http
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Additional context**

`vd --version`: `saul.pw/VisiData v1.5.2`

CC @7c6f434c, who's listed as the maintainer of the visidata NixOS package

**Comment by anjakefala** [comment]
Hi! =)

There are a lot of data format loaders, most with their own dependencies, and we made a decision to not have any of the dependencies install by default. We left it with the package maintainers to decide which they wanted to include in the various packages. 

If you think `requests` should be included in the NixOS one by default, their repo is the place [to write the issue](https://github.com/NixOS/nixpkgs/issues/new). That is actually one of the packages that I do not maintain. I am not familiar enough with NixOS to be able to write for you a workaround. =(

**Comment by 7c6f434c** [comment]
@WesleyAC `visidata.overrideAttrs (x: { propagatedBuildInputs = x.propagatedBuildInputs ++ (with python3Packages; [requests]);})` (I would comment in a Nixpkgs issue if there was one…)
