### ISSUE TITLE
[develop fixed format] Fixed format has a traceback if --fixed_rows is less than --skip

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#439]
**Small description**
Fixed format has a traceback  if --fixed_rows is less than --skip 15

This command gives a traceback: vd -f fixed --fixed-rows 10 --skip 15

**Expected result**
Fixed-rows applies after the initial lines are skipped.

**Actual result with screenshot**
```
Traceback (most recent call last):
   File "/usr/lib/python3/site-packages/visidata/threads.py", line 202, in _toplevelTryFunc
     t.status = func(*args, **kwargs)
   File "/usr/lib/python3/site-packages/visidata/sheets.py", line 828, in reload
     list(self.optlines(itsource, 'skip'))
   File "/usr/lib/python3/site-packages/visidata/sheets.py", line 817, in optlines
     yield next(it)
   File "/usr/lib/python3/site-packages/visidata/loaders/fixed_width.py", line 67, in iterload
     self.setColNames(self.headerlines)
 AttributeError: 'FixedWidthColumnsSheet' object has no attribute 'headerlines'        
```

**Steps to reproduce with sample data and a .vd**
vd -f fixed --fixed-rows 10 --skip 15

**Additional context**
Please include the version of VisiData.
latest head from develop v2.3

**Comment by frosencrantz** [comment]
@anjakefala  & @saulpw  This stack trace also happens if there is no input in fixed mode:
```
vd -f fixed - < /dev/null
```

**Comment by saulpw** [comment]
Thanks @frosencrantz, it's amazing what the right repro can do ;)
