### ISSUE TITLE
[develop] Can't connect to postgresql db

### ISSUE THREAD

**Issue by sfranky** [saulpw/visidata#485]
**Small description**

I try to connect to a postgresql database with
```
vd postgres://<user>:<passwd>@IP:PORT/dbname
```

**Actual result with screenshot**

```
Traceback (most recent call last):
  File "/usr/local/bin/vd", line 4, in <module>
    __import__('pkg_resources').run_script('visidata===2.-3dev', 'vd')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/visidata-2._3dev-py3.6.egg/EGG-INFO/scripts/vd", line 6, in <module>
  File "/usr/local/lib/python3.6/site-packages/visidata-2._3dev-py3.6.egg/visidata/main.py", line 215, in vd_cli
  File "/usr/local/lib/python3.6/site-packages/visidata-2._3dev-py3.6.egg/visidata/main.py", line 139, in main_vd
  File "/usr/local/lib/python3.6/site-packages/visidata-2._3dev-py3.6.egg/visidata/vdobj.py", line 37, in _vdfunc
  File "/usr/local/lib/python3.6/site-packages/visidata-2._3dev-py3.6.egg/visidata/data.py", line 193, in openSource
  File "/usr/local/lib/python3.6/site-packages/visidata-2._3dev-py3.6.egg/visidata/data.py", line 158, in openPath
  File "/usr/local/lib/python3.6/site-packages/visidata-2._3dev-py3.6.egg/visidata/loaders/postgres.py", line 21, in openurl_postgres
  File "/usr/local/lib/python3.6/site-packages/visidata-2._3dev-py3.6.egg/visidata/path.py", line 77, in __getattr__
AttributeError: 'PosixPath' object has no attribute 'path'
```

**Additional context**
Latest dev version, installed with pipx. and all dependencies.
Python 3.6.8
CentOS 7

**Comment by anjakefala** [comment]
This should now be fixed on the `develop` branch! https://github.com/saulpw/visidata/commit/984b03a9049c9803b09f1e80735e4424832f7307

Can you please verify, @sfranky? =)
