### ISSUE TITLE
[defer] Stack trace on 'NoneType' object has no attribute 'defer'

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#581]
**Small description**
Getting a stack trace when transposing a table.

**Description**
Transpose a data sheet.  For example, read the sample_data/StatusPR.csv  file, and tranpose.
All the cells in the first column report:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/visidata/basesheet.py", line 127, in execCommand
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "pyobj-cell", line 1, in <module>
    import math
  File "/usr/lib/python3.8/site-packages/visidata/basesheet.py", line 30, in __getitem__
    return getattr(obj, k)
  File "/usr/lib/python3.8/site-packages/visidata/sheets.py", line 419, in cursorValue
    return self.cursorCol.getValue(self.cursorRow)
  File "/usr/lib/python3.8/site-packages/visidata/column.py", line 182, in getValue
    if self.sheet.defer:
AttributeError: 'NoneType' object has no attribute 'defer'
```

**Expected result**
Transpose a table, column names in the first column.  But all cells have an exception.

**Steps to reproduce with sample data and a .vd**
Load sample_data/StatusPR.csv and transpose.

**Additional context**

Please include the version of VisiData latest develop version.

**Comment by anjakefala** [comment]
Nice find @frosencrantz!

Thanks for the bug report. :blush: This should be fixed now.
