### ISSUE TITLE
Cannot open .txt file

### ISSUE THREAD

**Issue by ecerami** [saulpw/visidata#60]
I am not sure if this is a bug or I am just not using the correct command line parameters.

If I open a file called iris.csv, like so:

vd iris.csv

the file opens up fine.

However, if I open the same exact file with a txt extension, e.g.:

vd iris.txt

I get the following trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/vd", line 39, in <module>
    main()
  File "/usr/local/bin/vd", line 36, in main
    visidata.run(sources)
  File "/usr/local/lib/python3.5/site-packages/visidata/vd.py", line 1857, in run
    ret = wrapper(curses_main, sheetlist)
  File "/usr/local/lib/python3.5/site-packages/visidata/vd.py", line 1772, in wrapper
    return curses.wrapper(setupcolors, f, *args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.5/site-packages/visidata/vd.py", line 1768, in setupcolors
    return f(stdscr, *args)
  File "/usr/local/lib/python3.5/site-packages/visidata/vd.py", line 1863, in curses_main
    vd().push(vs)  # first push does a reload
  File "/usr/local/lib/python3.5/site-packages/visidata/vd.py", line 550, in push
    vs.reload()
  File "/usr/local/lib/python3.5/site-packages/visidata/vd.py", line 1504, in reload
    self.add_line(L[:-1])
  File "/usr/local/lib/python3.5/site-packages/visidata/vd.py", line 1510, in add_line
    self.rows.extend(textwrap.wrap(text, width=windowWidth-2))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

p.s.  thanks for making VisiData!

**Comment by saulpw** [comment]
As a .txt file, the data should be loaded in a text viewer (unless it has tabs in the first line, in which case it is parsed as a .tsv file).  To load as a .csv, use `vd -f csv iris.txt`.

I will fix the issue that prevents it from being loaded in the text viewer.
