### ISSUE TITLE
[starting] Crashes w/traceback when starting Visidata without a ~/.visidata/plugins directory

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#614]
**Small description**
Traceback when starting Visidata without a ~/.visidata/plugins directory

**Expected result**
Starts running

**Actual result with screenshot**
```
Traceback (most recent call last):
  File "/usr/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/usr/lib/python3.8/site-packages/visidata/main.py", line 220, in vd_cli
    rc = main_vd()
  File "/usr/lib/python3.8/site-packages/visidata/main.py", line 75, in main_vd
    args = vd.parseArgs(parser)
  File "/usr/lib/python3.8/site-packages/visidata/settings.py", line 312, in parseArgs
    addGlobals(importlib.import_module(modname).__dict__)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugins'
```

**Steps to reproduce with sample data and a .vd**
$ vd

**Additional context**
Please include the version of VisiData: Latest version of develop

**Comment by anjakefala** [comment]
Thanks! =) Should be fixed.

**Comment by frosencrantz** [comment]
Awesome!  So fast.
