### ISSUE TITLE
[dir] Directory viewer stack traces when opening directory with an extension.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#629]
**Small description**
No longer able to open directories with '.' in the name

**Expected result**
Open directory

**Actual result with screenshot**
Directory is not opened, and stack trace.

**Steps to reproduce with sample data and a .vd**
Looks like one of the "Two hard things in CS"
```
touch t.foo
vd .
```
Hit enter on t.foo

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/visidata/basesheet.py", line 128, in execCommand
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "open-row", line 1, in <module>
    import math
  File "/usr/lib/python3.8/site-packages/visidata/data.py", line 175, in openSource
    vs = vs or vd.openPath(p, filetype=filetype)
  File "/usr/env/lib/python3.8/site-packages/visidata/data.py", line 158, in openPath
    return openfunc(p)
  File "//lib/python3.8/site-packages/visidata/data.py", line 186, in open_txt
    with p.open_text() as fp:
  File "/usr/lib/python3.8/site-packages/visidata/path.py", line 117, in open_text
    return self.open(mode=mode, encoding=options.encoding, errors=options.encoding_errors)
  File "/usr/lib/python3.8/site-packages/visidata/path.py", line 139, in open
    return self._path.open(*args, **kwargs)
  File "/usr/lib/python3.8/pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
IsADirectoryError: [Errno 21] Is a directory: 't.foo'
```
**Additional context**
Please include the version of VisiData. Latest version of develop.

**Comment by anjakefala** [comment]
Fixed! Nice find. Thanks for the bug report.

**Comment by frosencrantz** [comment]
Thank you, @anjakefala!  I use this a lot.
