### ISSUE TITLE
[pyobj-cell]  Trying to pyobj-cell on a list stack traces

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#667]
**Small description**
[pyobj-cell]  Trying to pyobj-cell on a list stack traces

**Expected result**
Dives into list.

**Actual result with screenshot**

https://asciinema.org/a/uxKjWFMGdGcBgMlOy9upipihc
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/visidata/basesheet.py", line 132, in execCommand
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "pyobj-cell", line 1, in <module>
    import math
  File "/usr/lib/python3.8/site-packages/visidata/pyobj.py", line 125, in push_pyobj
    vs = load_pyobj(name, source=pyobj)
  File "/usr/lib/python3.8/site-packages/visidata/vdobj.py", line 37, in _vdfunc
    return func(visidata.vd, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/visidata/pyobj.py", line 142, in load_pyobj
    return SheetList(*names, **kwargs)
TypeError: SheetList() missing 1 required positional argument: 'src'
```

**Steps to reproduce with sample data and a .vd**

```
echo '[[1,2,3]]' | vd -f json
```
Type z Ctrl-Y  pyobj-cell

**Additional context**
Please include the version of VisiData. Latest version from develop branch

**Comment by anjakefala** [comment]
Fixed in this commit a870943c97b0d =)
