### ISSUE TITLE
[v2.5] gO throws uncaught error

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#676]
**Small description**
If I open any sheet and `gO` I get the error below. I have tried this whilst my plugins are disabled and get the same.

**Expected result**
For the exception to be caught within vd (and shown in `vd.status`)

**Steps to reproduce with sample data and a .vd**
- `vd .`
- type `gO`

```
Traceback (most recent call last):
  File "/Users/geekscrapy/Documents/pyv/py3/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/Users/geekscrapy/Documents/pyv/py3/lib/python3.7/site-packages/visidata/main.py", line 291, in vd_cli
    rc = main_vd()
  File "/Users/geekscrapy/Documents/pyv/py3/lib/python3.7/site-packages/visidata/main.py", line 257, in main_vd
    run(vd.sheets[0])
  File "/Users/geekscrapy/Documents/pyv/py3/lib/python3.7/site-packages/visidata/mainloop.py", line 224, in run
    ret = wrapper(cursesMain, sheetlist)
  File "/Users/geekscrapy/Documents/pyv/py3/lib/python3.7/site-packages/visidata/mainloop.py", line 214, in wrapper
    return curses.wrapper(setupcolors, f, *args)
  File "/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/curses/__init__.py", line 102, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/geekscrapy/Documents/pyv/py3/lib/python3.7/site-packages/visidata/mainloop.py", line 211, in setupcolors
    return f(stdscr, *args)
  File "/Users/geekscrapy/Documents/pyv/py3/lib/python3.7/site-packages/visidata/mainloop.py", line 238, in cursesMain
    return vd.mainloop(_scr)
  File "/Users/geekscrapy/Documents/pyv/py3/lib/python3.7/site-packages/visidata/mainloop.py", line 177, in mainloop
    sheet.execCommand(self.keystrokes, keystrokes=self.keystrokes)
  File "/Users/geekscrapy/Documents/pyv/py3/lib/python3.7/site-packages/visidata/basesheet.py", line 138, in execCommand
    err = vd.exceptionCaught(e)
  File "/Users/geekscrapy/Documents/pyv/py3/lib/python3.7/site-packages/visidata/basesheet.py", line 132, in execCommand
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "open-config", line 1, in <module>
  File "/Users/geekscrapy/Documents/pyv/py3/lib/python3.7/site-packages/visidata/data.py", line 188, in open_txt
    with p.open_text() as fp:
AttributeError: 'str' object has no attribute 'open_text'
```

**Comment by anjakefala** [comment]
Thanks @geekscrapy for the bug report! Should be fixed on `develop` now. =)
