### ISSUE TITLE
Uncaught exception if splitwin-swap, -g and --debug is used when only one sheet in stack

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#679]
**Small description**
When `-g` and `--debug` are used as cli args and there is only one sheet in the stack, and `splitwin-swap`/`TAB` is commanded/pressed, a critical, uncaught exception is raised and `vd` exits.

**Expected result**
For a status to show stating `IndexError: list index out of range` like normal. 

**Actual result with screenshot**
Exception is below

```
Traceback (most recent call last):
  File "/Users/geekscrapy/Documents/pyv/py3.7/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/main.py", line 291, in vd_cli
    rc = main_vd()
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/main.py", line 257, in main_vd
    run(vd.sheets[0])
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/mainloop.py", line 224, in run
    ret = wrapper(cursesMain, sheetlist)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/mainloop.py", line 214, in wrapper
    return curses.wrapper(setupcolors, f, *args)
  File "/usr/local/Cellar/python@3.7/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/mainloop.py", line 211, in setupcolors
    return f(stdscr, *args)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/mainloop.py", line 238, in cursesMain
    return vd.mainloop(_scr)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/mainloop.py", line 177, in mainloop
    sheet.execCommand(self.keystrokes, keystrokes=self.keystrokes)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/basesheet.py", line 138, in execCommand
    err = vd.exceptionCaught(e)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/basesheet.py", line 132, in execCommand
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "splitwin-swap", line 1, in <module>
IndexError: list index out of range
```

**Comment by anjakefala** [comment]
Hi @geekscrapy! 

The uncaught exception is expected behaviour for `--debug`. =) That is intentional with its usage.

However, you did catch a bug with it! I pushed a fix to `develop`. splitwin-swap will now handle cases of <2 sheets.
