### ISSUE TITLE
[v2.-5dev] pyobj-row on freq sheet throws error

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#686]
To reproduce:

1. Create a frequency sheet
2. Run command `pyobj-row`

```
Traceback (most recent call last):
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/basesheet.py", line 132, in execCommand
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "pyobj-row", line 1, in <module>
    import math
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/pyobj.py", line 125, in push_pyobj
    vs = load_pyobj(name, source=pyobj)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/vdobj.py", line 37, in _vdfunc
    return func(visidata.vd, *args, **kwargs)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/pyobj.py", line 140, in load_pyobj
    return SheetNamedTuple(*names, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'src'
```

**Comment by anjakefala** [comment]
Thanks for the bug report!

This has now been fixed in https://github.com/saulpw/visidata/commit/94c72b3db179f42cac439012de9835cb6f500a6f =)
