### ISSUE TITLE
[binning] Stack trace when numeric binning vlen column

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#690]
**Small description**
Stack trace when numeric binning vlen column

**Expected result**
Creates a binned frequency table

**Actual result with screenshot**
https://asciinema.org/a/6yN4Bjy1mqpIBPHw0UYygYuYL
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/visidata/threads.py", line 207, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/visidata/pivot.py", line 203, in groupRows
    numericGroupRows = {formatRange(numericCols[0], numRange): PivotGroupRow(discreteKeys, numRange, [], {}) for numRange in numericBins}
  File "/usr/lib/python3.8/site-packages/visidata/pivot.py", line 203, in <dictcomp>
    numericGroupRows = {formatRange(numericCols[0], numRange): PivotGroupRow(discreteKeys, numRange, [], {}) for numRange in numericBins}
  File "/usr/lib/python3.8/site-packages/visidata/pivot.py", line 25, in formatRange
    nankey = makeErrorKey(col)
  File "/usr/lib/python3.8/site-packages/visidata/pivot.py", line 21, in makeErrorKey
    return col.type()
TypeError: __new__() missing 1 required positional argument: 'v'
```

**Steps to reproduce with sample data and a .vd**
```
$ vd  -g --numeric-binning benchmark.csv
```

```
sheet	col	row	longname	input	keystrokes	comment
			open-file	benchmark.csv	o	
benchmark	Customer		type-len		z#	set type of current column to len
benchmark	Customer		freq-col		F	open Frequency Table grouped on current column, with aggregations of other columns
```

**Additional context**
Please include the version of VisiData.  Latest develop version.

**Comment by anjakefala** [comment]
Thanks for the bug report @frosencrantz! This should be fixed on develop now.

**Comment by frosencrantz** [comment]
Too bad you can not count these for the Bug Off!  Thanks, @anjakefala!
