### ISSUE TITLE
Inner files are treated as -f foo type

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#740]
**Small description**
When trying to open a file which does not have the `.zip` extension (but is actually a zip) I use `vd -f zip foo.bar`. The file opens fine and I can see the inner files, however when I attempt to open one of them with ` ENTER` vd tries to open it as zip type (even if it has it's own extension) and throws the following exception (I have a zip file with manifest.json inside it):
```
Traceback (most recent call last):
  File "/Users/matthew.holley/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/threads.py", line 215, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/sheets.py", line 269, in reload
    for r in self.iterload():
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/loaders/archive.py", line 46, in iterload
    with zipfile.ZipFile(str(self.source), 'r') as zf:
  File "/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'manifest.json'
```

**Expected result**
vd opens a subsheet with the file extension relevant loader. In the case above, json.

**Steps to reproduce with sample data and a .vd**
Open a zip file with `vd -f zip anyfile.zip` and then try and open an inner file

Using vd commit 6a304df4de6bf008bce06d9821a3ef6bbca4f4bc

**Comment by anjakefala** [comment]
Hi @geekscrapy!

This is actually a feature, not a bug: https://github.com/saulpw/visidata/issues/523. I agree that that makes the situation tricky where you have a `zip` file not appended with `.zip`. I think wanting to control the filetype of the inner files is the more common desire.

Maybe @saulpw has something to add on how we might make this better down the road, but for now, this is the design we are going with.
