### ISSUE TITLE
[v2.0.1] Maybe a bug - memory usage climbs to 99% while union two sheets

### ISSUE THREAD

**Issue by bob-u** [saulpw/visidata#763]
**Small description**
How do I report possible memory leak?  I am trying to 'union' two sheets (each file 300MB large), progress stops at 50% grouping... (when it stops memory usage is about 3GB) while memory usage keeps on climbing to 99% (16GB).  Pressing ctrl-D or C or Z does nothing.  Each file can be opened separately and has the same number of columns, tab delimited.
**Expected result**

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.
visidata file1 file2
shift+s
select both sheets
press &
select full
**Additional context**
Please include the version of VisiData.

**Comment by bob-u** [comment]
Sometimes union completes however row count does not look right.  There's also additional column...

![example](https://user-images.githubusercontent.com/61708771/97651417-54e65400-1a32-11eb-80fa-48d36ecafe11.PNG)

I also have another issue that might be related (something wrong with parsing?):

when I open file1 by itself I can find all the records
when I open file1 and file2 then select file1 sheet
sheet opens (lists proper number of rows) yet I'm unable to find some entries when doing regex search

**Comment by saulpw** [comment]
I don't know, @bob-u.  There's not enough information here to diagnose the issue, though it sounds like it might be something memory-related. Open another issue if you find a definite problem.

**Comment by bob-u** [comment]
Maybe it's a loader problem.  Some of the files are parsed into 20 columns where really it should be 4.  When files are being merged, 4 columns are merged first and then 16 columns are added to every row, exhausting memory.

I also been getting exceptions:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\user\appdata\local\programs\python\python37\lib\threading.py", line 927, in _bootstrap_inner
    (self.name, _format_exc()), file=_sys.stderr)
  File "c:\users\user\appdata\local\programs\python\python37\lib\traceback.py", line 167, in format_exc
  File "c:\users\user\appdata\local\programs\python\python37\lib\traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "c:\users\user\appdata\local\programs\python\python37\lib\traceback.py", line 508, in __init__
    capture_locals=capture_locals)
  File "c:\users\user\appdata\local\programs\python\python37\lib\traceback.py", line 363, in extract
    f.line
  File "c:\users\user\appdata\local\programs\python\python37\lib\traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "c:\users\user\appdata\local\programs\python\python37\lib\linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "c:\users\user\appdata\local\programs\python\python37\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "c:\users\user\appdata\local\programs\python\python37\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "c:\users\user\appdata\local\programs\python\python37\lib\tokenize.py", line 447, in open
    buffer = _builtin_open(filename, 'rb')
visidata.EscapeException
 
Since above exception, I upgraded to development branch and pythin3.9 but continue getting same issue.
