### ISSUE TITLE
AttributeError: 'Chartsheet' object has no attribute 'iter_rows'

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#797]
**Small description**
Hi,
when I run `vd _20112020100242.xlsx +:tavola_pop_res01::`, I have 

```
AttributeError: 'Chartsheet' object has no attribute 'iter_rows' 
```

The file is this [_20112020100242.xlsx](https://github.com/saulpw/visidata/files/5575090/_20112020100242.xlsx).

vd open it, but if I try do simply a format conversion using `vd _20112020100242.xlsx +:tavola_pop_res01:: -b -o ./output.csv`

I have

```
opening _20112020100242.xlsx as xlsx
Traceback (most recent call last):
  File "/home/aborruso/.local/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/main.py", line 298, in vd_cli
    rc = main_vd()
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/main.py", line 228, in main_vd
    vd.push(sources[0])
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/sheets.py", line 982, in push
    vs.ensureLoaded()
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/basesheet.py", line 189, in ensureLoaded
    return self.reload()   # likely launches new thread
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/vdobj.py", line 20, in _execAsync
    return visidata.vd.execAsync(func, *args, **kwargs)
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/main.py", line 198, in <lambda>
    vd.execAsync = lambda func, *args, **kwargs: func(*args, **kwargs) # disable async
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/sheets.py", line 269, in reload
    for r in self.iterload():
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/loaders/xlsx.py", line 26, in iterload
    vs.reload()
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/vdobj.py", line 20, in _execAsync
    return visidata.vd.execAsync(func, *args, **kwargs)
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/main.py", line 198, in <lambda>
    vd.execAsync = lambda func, *args, **kwargs: func(*args, **kwargs) # disable async
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/sheets.py", line 884, in reload
    self.setCols(list(self.optlines(itsource, 'header')))
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/sheets.py", line 870, in optlines
    yield next(it)
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/loaders/xlsx.py", line 33, in iterload
    for row in Progress(worksheet.iter_rows(), total=worksheet.max_row or 0):
AttributeError: 'Chartsheet' object has no attribute 'iter_rows'
```

**Expected result**

To open and save it without error

**Actual result with screenshot**

```
Traceback (most recent call last):
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/threads.py", line 215, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/sheets.py", line 884, in reload
    self.setCols(list(self.optlines(itsource, 'header')))
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/sheets.py", line 870, in optlines
    yield next(it)
  File "/home/aborruso/.local/lib/python3.8/site-packages/visidata/loaders/xlsx.py", line 33, in iterload
    for row in Progress(worksheet.iter_rows(), total=worksheet.max_row or 0):
AttributeError: 'Chartsheet' object has no attribute 'iter_rows'
```

**Additional context**
I have the latest saul.pw/VisiData v2.0+

**Comment by aborruso** [comment]
A strange thing: if I open and save the xlsx file using libreoffice calc, and than try to run the same vd command, I have no error

**Comment by aborruso** [comment]
@saulpw am I the only one that has this error using this file?

Thank you

**Comment by saulpw** [comment]
Hi @aborruso, there is a Chart in the xlsx file (Libreoffice must not save the chart).  I made a small change so vd doesn't automatically reload non-Workbooks.  This should fix the issue with converting.

**Comment by aborruso** [comment]
Thank you, it works
