### ISSUE TITLE
 [vds] Problems with vds format container columns

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#885]
**Small description**
The vds format don't handle container columns (expanded or unexpanded)

**Expected result**
Works like the original data plus the extra vds features

**Actual result with screenshot**

https://asciinema.org/a/YVhEi56JmsqCO5il6948gsuyS

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/threads.py", line 215, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 284, in reload
    for r in self.iterload():
  File "/usr/lib/python3.9/site-packages/visidata/loaders/vds.py", line 71, in iterload
    c = globals()[classname](d.pop('name'))
KeyError: 'ExpandedColumn'
```

**Steps to reproduce with sample data and a .vd**

Load this json file, and save as vds. For stack trace first expand column b, save the data vds, then load the vds file.

```
{"a":1,"b":[0,1],"c":null}
{"a":2,"b":[0,1,2],"c":null}
{"a":3,"b":[0,1,2,3],"c":null}
```

unexpanded the b column data is lost and replaced with the string '[2]' etc.:

```json
#{"name": "-"}
#{"name": "a", "width": 4, "height": 1, "expr": "a", "keycol": 0, "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "int", "col": "Column"}
#{"name": "b", "width": 5, "height": 1, "expr": "b", "keycol": 0, "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "", "col": "Column"}
#{"name": "c", "width": 4, "height": 1, "expr": "c", "keycol": 0, "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "", "col": "Column"}
{"a": "1", "b": "[2]", "c": ""}
{"a": "2", "b": "[3]", "c": ""}
{"a": "3", "b": "[4]", "c": ""}
```

The expanded version has the data but can only be partially loaded, reporting the stack trace above.
```json
#{"name": "-"}
#{"name": "a", "width": 4, "height": 1, "expr": "a", "keycol": 0, "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "int", "col": "Column"}
#{"name": "b[0]", "width": 6, "height": 1, "expr": null, "keycol": 0, "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "int", "col": "ExpandedColumn"}
#{"name": "b[1]", "width": 6, "height": 1, "expr": null, "keycol": 0, "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "int", "col": "ExpandedColumn"}
#{"name": "b[2]", "width": 6, "height": 1, "expr": null, "keycol": 0, "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "int", "col": "ExpandedColumn"}
#{"name": "b[3]", "width": 6, "height": 1, "expr": null, "keycol": 0, "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "int", "col": "ExpandedColumn"}
#{"name": "c", "width": 4, "height": 1, "expr": "c", "keycol": 0, "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "", "col": "Column"}
{"a": "1", "b[0]": "0", "b[1]": "1", "b[2]": "", "b[3]": "", "c": ""}
{"a": "2", "b[0]": "0", "b[1]": "1", "b[2]": "2", "b[3]": "", "c": ""}
{"a": "3", "b[0]": "0", "b[1]": "1", "b[2]": "2", "b[3]": "3", "c": ""}
```

**Additional context**
Please include the version of VisiData. Latest develop version.

**Comment by frosencrantz** [comment]
Related discussion: https://github.com/saulpw/visidata/discussions/886

**Comment by saulpw** [comment]
Thanks, @frosencrantz.  This is what convinced me that we had to save typed values.
