### ISSUE TITLE
JSON Loader doesn't handle UTF-8 BOM

### ISSUE THREAD

**Issue by daviewales** [saulpw/visidata#908]
**Small description**
I tried to load a JSON dataset directly from the url as follows

    vd https://data.nsw.gov.au/data/dataset/0a52e6c1-bc0b-48af-8b45-d791a6d8e289/resource/f3a28eed-8c2a-437b-8ac1-2dab3cf760f9/download/covid-case-locations-20210217.json

**Expected result**
I expected it to load as a table.

**Actual result with screenshot**
I get the following error:

``` python
Traceback (most recent call last):
  File "/Users/dwales/.local/pipx/venvs/visidata/lib/python3.9/site-packages/visidata/loaders/json.py", line 31, in iterload
    ret = json.loads(L)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 335, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dwales/.local/pipx/venvs/visidata/lib/python3.9/site-packages/visidata/threads.py", line 215, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/Users/dwales/.local/pipx/venvs/visidata/lib/python3.9/site-packages/visidata/sheets.py", line 284, in reload
    for r in self.iterload():
  File "/Users/dwales/.local/pipx/venvs/visidata/lib/python3.9/site-packages/visidata/loaders/json.py", line 43, in iterload
    ret = json.load(fp)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 335, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
```

**Steps to reproduce with sample data and a .vd**

`errors.vd`:

```
sheet	col	row	longname	input	keystrokes	comment
			open-file	https://data.nsw.gov.au/data/dataset/0a52e6c1-bc0b-48af-8b45-d791a6d8e289/resource/f3a28eed-8c2a-437b-8ac1-2dab3cf760f9/download/covid-case-locations-20210217.json	o	

```

**Additional context**
Please include the version of VisiData.

saul.pw/VisiData v2.2.1

Note: I'm aware that including a BOM in a JSON file is technically invalid. However, I feel that it would be nice if `visidata` automatically removed the BOM before trying to parse the JSON (or perhaps caught the error, and retried after removing the BOM).

**Comment by saulpw** [comment]
Hi @daviewales, thanks for the feature request.  It's a reasonable thing for VisiData to detect a UTF-8 BOM as the first bytes and strip them, not just for JSON but for all text formats.  I've updated the related #200 and added it to the wishlist.

Kondo'ed for now.

**Comment by daviewales** [comment]
@saulpw Thanks for linking #200. It gave me the hint I needed to find `path.py`!

**Comment by saulpw** [comment]
Now that we have a separate `options.save_encoding`, I changed the default for o`ptions.encoding` to `utf-8-sig` which should detect the BOM and skip it. Thanks for the idea, @daviewales!

**Comment by daviewales** [comment]
Thank you!
