### ISSUE TITLE
[sqlite] How to load a specific table via the command line?

### ISSUE THREAD

**Issue by jwhetzel-gpc** [saulpw/visidata#949]
Hello!  I see examples in the help for using the "+" syntax when opening things like Excel files to specific sheets.  I would like to do something similar with sqlite, opening to a specified table, but I've been unsuccessful in doing so.

I have tried `vd -f sqlite mydatabase.db +my_table_name` but when vd loads, it loads the full table list and a message at the bottom says `mydatabase has no row "my_table_name"`.  I've verified that the table actually does exist, is spelled correctly, etc.

I also tried `vd -f sqlite mydatabase.db +:my_table_name` (adding a colon before the table name) as I thought maybe a table would be considered a subsheet rather than a toplevel, but that crashes with a TypeError: 

```
Traceback (most recent call last):
  File "/Users/mbp-jwhetzel/.pyenv/versions/3.7.6/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/Users/mbp-jwhetzel/.pyenv/versions/3.7.6/Python.framework/Versions/3.7/lib/python3.7/site-packages/visidata/main.py", line 301, in vd_cli
    rc = main_vd()
  File "/Users/mbp-jwhetzel/.pyenv/versions/3.7.6/Python.framework/Versions/3.7/lib/python3.7/site-packages/visidata/main.py", line 165, in main_vd
    startsheet = [Path(inputs[-1]).name] if inputs else None
  File "/Users/mbp-jwhetzel/.pyenv/versions/3.7.6/Python.framework/Versions/3.7/lib/python3.7/site-packages/visidata/path.py", line 57, in __init__
    self.given = os.path.expandvars(os.path.expanduser(given))
  File "/Users/mbp-jwhetzel/.pyenv/versions/3.7.6/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 235, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not tuple
```

Thanks!

**Comment by jwhetzel-gpc** [comment]
Nevermind!  I found how to load it.  Per discussion in  #214 I had to format it as `+:my_table_name:1:1`.  The help said that all parts of the "+" argument are optional, so I was confused by that.  So maybe an update to the help is required?  Or an example for sqlite?

**Comment by saulpw** [comment]
Hi @jwhetzel-gpc, I agree that the docs are confusing.  I think what it means (what I guess I meant when I wrote it :) is that you can use `+:my_table_name::` (i.e. the fields are optional but the colons aren't).

There's some tricky parsing code in there to do something sensible with varying numbers of colons but as you can see it's not very robust nor very helpful when it fails. I'd love to clean this up but it will require no small amount of diligence to enumerate all the cases and what should happen for each.
