### ISSUE TITLE
NameError: name 'inputPath' is not defined | "save-col"

### ISSUE THREAD

**Issue by savulchik** [saulpw/visidata#962]
**Small description**

When I enter save-col or save-col-keys commands I get the following error message:
`NameError: name 'inputPath' is not defined | "save-col"`

**Expected result**
Filename dialog is shown.

**Actual result with screenshot**
```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/visidata/2.4/libexec/lib/python3.9/site-packages/visidata/basesheet.py", line 154, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/opt/homebrew/Cellar/visidata/2.4/libexec/lib/python3.9/site-packages/visidata/basesheet.py", line 66, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "save-col", line 1, in <module>
    import math
  File "/opt/homebrew/Cellar/visidata/2.4/libexec/lib/python3.9/site-packages/visidata/save.py", line 92, in save_cols
    path = inputPath('save %s to: ' % savedcoltxt, value=vs.getDefaultSaveName())
NameError: name 'inputPath' is not defined
```

**Steps to reproduce with sample data and a .vd**
[save-col.bug.vd.txt](https://github.com/saulpw/visidata/files/6363615/save-col.bug.vd.txt)

**Additional context**
`saul.pw/VisiData v2.4`

**Comment by saulpw** [comment]
Thanks for the report, @savulchik!  It's a minor fix and will be in the next release.
